// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"Another-Nikki/interact_hub/service/internal/client"
	"Another-Nikki/interact_hub/service/internal/conf"
	"Another-Nikki/interact_hub/service/internal/data_sqlite"
	"Another-Nikki/interact_hub/service/internal/server"
	"Another-Nikki/interact_hub/service/internal/service"
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, data *conf.Data, logger log.Logger, avatars *conf.Avatars, clientTimeout *conf.ClientTimeout) (*kratos.App, func(), error) {
	db := data_sqlite.NewSqliteDB(data)
	data_sqliteData, cleanup, err := data_sqlite.NewData(db)
	if err != nil {
		return nil, nil, err
	}
	problemRepo := data_sqlite.NewProblemRepo(data_sqliteData)
	problemService := service.NewProblemService(problemRepo)
	articleRepo := data_sqlite.NewArticleRepo(data_sqliteData)
	articleService := service.NewArticleService(articleRepo)
	commentRepo := data_sqlite.NewCommentImpl(data_sqliteData)
	commentService := service.NewCommentService(commentRepo)
	userRepo := data_sqlite.NewUserImpl(data_sqliteData)
	userService := service.NewUserService(userRepo, avatars)
	globalGrpcClient := client.NewGlobalGrpcClient(data, clientTimeout)
	codeDataRepo := data_sqlite.NewCodeProcessingImpl(data_sqliteData)
	codeProcessingService := service.NewCodeProcessingService(globalGrpcClient, codeDataRepo)
	logsRepo := data_sqlite.NewLogsRepoImpl(data_sqliteData)
	logsService := service.NewLogsService(logsRepo)
	grpcServer := server.NewGRPCServer(confServer, logger, problemService, articleService, commentService, userService, codeProcessingService, logsService)
	httpServer := server.NewHTTPServer(confServer, logger, problemService, codeProcessingService, userService, articleService, commentService, logsService)
	app := newApp(logger, grpcServer, httpServer)
	return app, func() {
		cleanup()
	}, nil
}
