// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"Another-Nikki/interact_hub/service/internal/conf"
	"Another-Nikki/interact_hub/service/internal/data"
	"Another-Nikki/interact_hub/service/internal/server"
	"Another-Nikki/interact_hub/service/internal/service"
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	db := data.NewMySql(confData)
	dataData, cleanup, err := data.NewData(db)
	if err != nil {
		return nil, nil, err
	}
	problemRepo := data.NewProblemRepo(dataData)
	problemService := service.NewProblemService(problemRepo)
	articleRepo := data.NewArticleRepo(dataData)
	articleService := service.NewArticleService(articleRepo)
	commentRepo := data.NewCommentImpl(db)
	commentService := service.NewCommentService(commentRepo)
	userRepo := data.NewUserImpl(dataData)
	userService := service.NewUserService(userRepo)
	discovery := data.NewDiscovery()
	globalGrpcClient := data.NewGlobalGrpcClient(confData, discovery)
	codeDataRepo := data.NewCodeProcessingImpl(dataData)
	codeProcessingService := service.NewCodeProcessingService(globalGrpcClient, codeDataRepo)
	grpcServer := server.NewGRPCServer(confServer, logger, problemService, articleService, commentService, userService, codeProcessingService)
	httpServer := server.NewHTTPServer(confServer, logger, problemService, codeProcessingService)
	registrar := data.NewRegistry()
	app := newApp(logger, grpcServer, httpServer, registrar)
	return app, func() {
		cleanup()
	}, nil
}
