version: '3'
services:
  mysql:
    image: mysql:latest
    container_name: mysql
    ports:
      - "3307:3306"       #后者是docker中的端口
    environment:
      - MYSQL_DATABASE=Another_Nikki
      - MYSQL_USER=jiyeon
      - MYSQL_PASSWORD=1234
      - MYSQL_ROOT_PASSWORD=1234

  canal-server:
    image: canal/canal-server
    container_name: canal-server
    ports:
      - 11111:11111
    volumes:
      - $PWD/docker-conf/canal/conf/:/home/admin/canal-server/conf/
      - $PWD/docker-conf/canal/logs/:/home/admin/canal-server/logs/
    depends_on:
      - mysql
      - kafka0

  kafka0:
    container_name: kafka0
    image: 'bitnami/kafka:3.5'
    ports:
      - '9092:9092'
      - '9093:9093'
    environment:
      ### 通用配置
      # 允许使用kraft，即Kafka替代Zookeeper
      - KAFKA_ENABLE_KRAFT=yes
      - KAFKA_CFG_NODE_ID=1
      # kafka角色，做broker，也要做controller
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      # 定义kafka服务端socket监听端口（Docker内部的ip地址和端口）
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      # 定义外网访问地址（宿主机ip地址和端口）ip不能是0.0.0.0
      # 两种方式查看自己本机的 ip
      # hostname -I
      # ip addr show eth0
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://192.168.1.100:9092
      # 定义安全协议
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      # CONTROLLER 投票者地址
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka0:9093
      # 指定供外部使用的控制类请求信息
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      # 设置broker最大内存，和初始内存
      - KAFKA_HEAP_OPTS=-Xmx512M -Xms256M
      # 使用Kafka时的集群id，集群内的Kafka都要用这个id做初始化，生成一个UUID即可(22byte)
      - KAFKA_KRAFT_CLUSTER_ID=xYcCyHmJlIaLzLoBzVwIcP
      # 允许不加密监听，默认false，不建议在生产环境使用
      - ALLOW_PLAINTEXT_LISTENER=yes
      # topic不存在时自动创建
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=false
      # broker.id，必须唯一，且与KAFKA_CFG_NODE_ID一致
      - KAFKA_BROKER_ID=1

  kafka-ui:
    container_name: kafka-ui
    image: provectuslabs/kafka-ui:latest
    ports:
      - 7766:8080
    environment:
      DYNAMIC_CONFIG_ENABLED: true
  elasticsearch:
    image: elasticsearch:8.6.0
    container_name: elasticsearch
    environment:
      - "cluster.name=elasticsearch" #设置集群名称为elasticsearch
      - "discovery.type=single-node" #以单一节点模式启动
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m" #设置使用jvm内存大小
      - "xpack.security.enabled=false"
    ports:
      - "9200:9200"
      - "9300:9300"
  kibana:
    image: kibana:8.6.0
    container_name: kibana
    links:
      - elasticsearch:es #可以用es这个域名访问elasticsearch服务
    depends_on:
      - elasticsearch #kibana在elasticsearch启动之后再启动
    environment:
      - "elasticsearch.hosts=http://es:9200" #设置访问elasticsearch的地址
      - "I18N_LOCALE=zh-CN"
    ports:
      - "5601:5601"

  Etcd:
    image: 'bitnami/etcd:latest'
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd:2379
    ports:
      - "2379:2379"
      - "2380:2380"
  jaeger-all-in-one:
    container_name: jaeger
    image: jaegertracing/all-in-one:1.53
    environment:
      - COLLECTOR_ZIPKIN_HOST_PORT=:9411
    ports:
      - "16686:16686"
      - "14268:14268"
      - "14250:14250"
      - "6831:6831"
      - "9411:9411"