version: '3'
services:
  mysql:
    image: mysql:latest
    container_name: mysql
    ports:
      - "3307:3306"       #后者是docker中的端口
    environment:
      - MYSQL_DATABASE=Another_Nikki
      - MYSQL_USER=jiyeon
      - MYSQL_PASSWORD=1234
      - TZ=Asia/Shanghai
      - MYSQL_ROOT_PASSWORD=1234

  Etcd:
    image: 'bitnami/etcd:latest'
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd:2379
    ports:
      - "2379:2379"
      - "2380:2380"
  jaeger-all-in-one:
    container_name: jaeger
    image: jaegertracing/all-in-one:1.53
    environment:
      - COLLECTOR_ZIPKIN_HOST_PORT=:9411
    ports:
      - "16686:16686"
      - "14268:14268"
      - "14250:14250"
      - "6831:6831"
      - "9411:9411"