version: '3'
services:
  mysql:
    image: mysql:latest
    ports:
      - "3307:3306"       #后者是docker中的端口
    environment:
      - MYSQL_DATABASE=Another_Nikki
      - MYSQL_USER=jiyeon
      - MYSQL_PASSWORD=1234
      - MYSQL_RANDOM_ROOT_PASSWORD="yes"

  cpp_environment:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./code:/dox       # 后者是 docker 中的，表示 code 和 dox 共享
    command: sh -c "g++ -o cpp c++.cpp && ./cpp > a.out"