version: '3'
services:
  mysql:
    image: mysql:latest
    ports:
      - "3307:3306"       #后者是docker中的端口
    environment:
      - MYSQL_DATABASE=Another_Nikki
      - MYSQL_USER=jiyeon
      - MYSQL_PASSWORD=1234
      - MYSQL_RANDOM_ROOT_PASSWORD="yes"

  zookeeper:
    image: zookeeper
    ports:
      - "2181:2181"
#    volumes:
#      - zookeeper_vol:/data
#      - zookeeper_vol:/datalog
#      - zookeeper_vol:/logs
    container_name: zookeeper

  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: "localhost"
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_LOG_DIRS: "/kafka/logs"
#    volumes:
#      - kafka_vol:/kafka
    depends_on:
      - zookeeper
    container_name: kafka