// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: code_processing.proto

package api

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type SubmitCodeReq struct {
	UserId               int64    `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	UserName             string   `protobuf:"bytes,2,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	ProblemId            int64    `protobuf:"varint,3,opt,name=problem_id,json=problemId,proto3" json:"problem_id,omitempty"`
	ProblemName          string   `protobuf:"bytes,4,opt,name=problem_name,json=problemName,proto3" json:"problem_name,omitempty"`
	Language             string   `protobuf:"bytes,5,opt,name=language,proto3" json:"language,omitempty"`
	Code                 string   `protobuf:"bytes,6,opt,name=code,proto3" json:"code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SubmitCodeReq) Reset()         { *m = SubmitCodeReq{} }
func (m *SubmitCodeReq) String() string { return proto.CompactTextString(m) }
func (*SubmitCodeReq) ProtoMessage()    {}
func (*SubmitCodeReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_49a73f4c69c844ba, []int{0}
}
func (m *SubmitCodeReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SubmitCodeReq.Unmarshal(m, b)
}
func (m *SubmitCodeReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SubmitCodeReq.Marshal(b, m, deterministic)
}
func (m *SubmitCodeReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SubmitCodeReq.Merge(m, src)
}
func (m *SubmitCodeReq) XXX_Size() int {
	return xxx_messageInfo_SubmitCodeReq.Size(m)
}
func (m *SubmitCodeReq) XXX_DiscardUnknown() {
	xxx_messageInfo_SubmitCodeReq.DiscardUnknown(m)
}

var xxx_messageInfo_SubmitCodeReq proto.InternalMessageInfo

func (m *SubmitCodeReq) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *SubmitCodeReq) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func (m *SubmitCodeReq) GetProblemId() int64 {
	if m != nil {
		return m.ProblemId
	}
	return 0
}

func (m *SubmitCodeReq) GetProblemName() string {
	if m != nil {
		return m.ProblemName
	}
	return ""
}

func (m *SubmitCodeReq) GetLanguage() string {
	if m != nil {
		return m.Language
	}
	return ""
}

func (m *SubmitCodeReq) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

type SubmitCodeResp struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SubmitCodeResp) Reset()         { *m = SubmitCodeResp{} }
func (m *SubmitCodeResp) String() string { return proto.CompactTextString(m) }
func (*SubmitCodeResp) ProtoMessage()    {}
func (*SubmitCodeResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_49a73f4c69c844ba, []int{1}
}
func (m *SubmitCodeResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SubmitCodeResp.Unmarshal(m, b)
}
func (m *SubmitCodeResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SubmitCodeResp.Marshal(b, m, deterministic)
}
func (m *SubmitCodeResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SubmitCodeResp.Merge(m, src)
}
func (m *SubmitCodeResp) XXX_Size() int {
	return xxx_messageInfo_SubmitCodeResp.Size(m)
}
func (m *SubmitCodeResp) XXX_DiscardUnknown() {
	xxx_messageInfo_SubmitCodeResp.DiscardUnknown(m)
}

var xxx_messageInfo_SubmitCodeResp proto.InternalMessageInfo

type UpdateCodeCompileStatusReq struct {
	CodeId               int64    `protobuf:"varint,1,opt,name=code_id,json=codeId,proto3" json:"code_id,omitempty"`
	Status               string   `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	CompileLog           string   `protobuf:"bytes,3,opt,name=compile_log,json=compileLog,proto3" json:"compile_log,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateCodeCompileStatusReq) Reset()         { *m = UpdateCodeCompileStatusReq{} }
func (m *UpdateCodeCompileStatusReq) String() string { return proto.CompactTextString(m) }
func (*UpdateCodeCompileStatusReq) ProtoMessage()    {}
func (*UpdateCodeCompileStatusReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_49a73f4c69c844ba, []int{2}
}
func (m *UpdateCodeCompileStatusReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateCodeCompileStatusReq.Unmarshal(m, b)
}
func (m *UpdateCodeCompileStatusReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateCodeCompileStatusReq.Marshal(b, m, deterministic)
}
func (m *UpdateCodeCompileStatusReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateCodeCompileStatusReq.Merge(m, src)
}
func (m *UpdateCodeCompileStatusReq) XXX_Size() int {
	return xxx_messageInfo_UpdateCodeCompileStatusReq.Size(m)
}
func (m *UpdateCodeCompileStatusReq) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateCodeCompileStatusReq.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateCodeCompileStatusReq proto.InternalMessageInfo

func (m *UpdateCodeCompileStatusReq) GetCodeId() int64 {
	if m != nil {
		return m.CodeId
	}
	return 0
}

func (m *UpdateCodeCompileStatusReq) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *UpdateCodeCompileStatusReq) GetCompileLog() string {
	if m != nil {
		return m.CompileLog
	}
	return ""
}

type UpdateCodeCompileStatusResp struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateCodeCompileStatusResp) Reset()         { *m = UpdateCodeCompileStatusResp{} }
func (m *UpdateCodeCompileStatusResp) String() string { return proto.CompactTextString(m) }
func (*UpdateCodeCompileStatusResp) ProtoMessage()    {}
func (*UpdateCodeCompileStatusResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_49a73f4c69c844ba, []int{3}
}
func (m *UpdateCodeCompileStatusResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateCodeCompileStatusResp.Unmarshal(m, b)
}
func (m *UpdateCodeCompileStatusResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateCodeCompileStatusResp.Marshal(b, m, deterministic)
}
func (m *UpdateCodeCompileStatusResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateCodeCompileStatusResp.Merge(m, src)
}
func (m *UpdateCodeCompileStatusResp) XXX_Size() int {
	return xxx_messageInfo_UpdateCodeCompileStatusResp.Size(m)
}
func (m *UpdateCodeCompileStatusResp) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateCodeCompileStatusResp.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateCodeCompileStatusResp proto.InternalMessageInfo

type UpdateCodeJudgeStatusReq struct {
	CodeId               int64    `protobuf:"varint,1,opt,name=code_id,json=codeId,proto3" json:"code_id,omitempty"`
	CompileStatus        string   `protobuf:"bytes,2,opt,name=compile_status,json=compileStatus,proto3" json:"compile_status,omitempty"`
	JudgeStatus          string   `protobuf:"bytes,3,opt,name=judge_status,json=judgeStatus,proto3" json:"judge_status,omitempty"`
	CpuTimeUsed          string   `protobuf:"bytes,4,opt,name=cpu_time_used,json=cpuTimeUsed,proto3" json:"cpu_time_used,omitempty"`
	MemoryUsed           string   `protobuf:"bytes,5,opt,name=memory_used,json=memoryUsed,proto3" json:"memory_used,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateCodeJudgeStatusReq) Reset()         { *m = UpdateCodeJudgeStatusReq{} }
func (m *UpdateCodeJudgeStatusReq) String() string { return proto.CompactTextString(m) }
func (*UpdateCodeJudgeStatusReq) ProtoMessage()    {}
func (*UpdateCodeJudgeStatusReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_49a73f4c69c844ba, []int{4}
}
func (m *UpdateCodeJudgeStatusReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateCodeJudgeStatusReq.Unmarshal(m, b)
}
func (m *UpdateCodeJudgeStatusReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateCodeJudgeStatusReq.Marshal(b, m, deterministic)
}
func (m *UpdateCodeJudgeStatusReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateCodeJudgeStatusReq.Merge(m, src)
}
func (m *UpdateCodeJudgeStatusReq) XXX_Size() int {
	return xxx_messageInfo_UpdateCodeJudgeStatusReq.Size(m)
}
func (m *UpdateCodeJudgeStatusReq) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateCodeJudgeStatusReq.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateCodeJudgeStatusReq proto.InternalMessageInfo

func (m *UpdateCodeJudgeStatusReq) GetCodeId() int64 {
	if m != nil {
		return m.CodeId
	}
	return 0
}

func (m *UpdateCodeJudgeStatusReq) GetCompileStatus() string {
	if m != nil {
		return m.CompileStatus
	}
	return ""
}

func (m *UpdateCodeJudgeStatusReq) GetJudgeStatus() string {
	if m != nil {
		return m.JudgeStatus
	}
	return ""
}

func (m *UpdateCodeJudgeStatusReq) GetCpuTimeUsed() string {
	if m != nil {
		return m.CpuTimeUsed
	}
	return ""
}

func (m *UpdateCodeJudgeStatusReq) GetMemoryUsed() string {
	if m != nil {
		return m.MemoryUsed
	}
	return ""
}

type UpdateCodeJudgeStatusResp struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateCodeJudgeStatusResp) Reset()         { *m = UpdateCodeJudgeStatusResp{} }
func (m *UpdateCodeJudgeStatusResp) String() string { return proto.CompactTextString(m) }
func (*UpdateCodeJudgeStatusResp) ProtoMessage()    {}
func (*UpdateCodeJudgeStatusResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_49a73f4c69c844ba, []int{5}
}
func (m *UpdateCodeJudgeStatusResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateCodeJudgeStatusResp.Unmarshal(m, b)
}
func (m *UpdateCodeJudgeStatusResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateCodeJudgeStatusResp.Marshal(b, m, deterministic)
}
func (m *UpdateCodeJudgeStatusResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateCodeJudgeStatusResp.Merge(m, src)
}
func (m *UpdateCodeJudgeStatusResp) XXX_Size() int {
	return xxx_messageInfo_UpdateCodeJudgeStatusResp.Size(m)
}
func (m *UpdateCodeJudgeStatusResp) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateCodeJudgeStatusResp.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateCodeJudgeStatusResp proto.InternalMessageInfo

func init() {
	proto.RegisterType((*SubmitCodeReq)(nil), "service.code_processing.api.SubmitCodeReq")
	proto.RegisterType((*SubmitCodeResp)(nil), "service.code_processing.api.SubmitCodeResp")
	proto.RegisterType((*UpdateCodeCompileStatusReq)(nil), "service.code_processing.api.UpdateCodeCompileStatusReq")
	proto.RegisterType((*UpdateCodeCompileStatusResp)(nil), "service.code_processing.api.UpdateCodeCompileStatusResp")
	proto.RegisterType((*UpdateCodeJudgeStatusReq)(nil), "service.code_processing.api.UpdateCodeJudgeStatusReq")
	proto.RegisterType((*UpdateCodeJudgeStatusResp)(nil), "service.code_processing.api.UpdateCodeJudgeStatusResp")
}

func init() { proto.RegisterFile("code_processing.proto", fileDescriptor_49a73f4c69c844ba) }

var fileDescriptor_49a73f4c69c844ba = []byte{
	// 484 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x53, 0xcd, 0x6a, 0x14, 0x41,
	0x10, 0xa6, 0xb3, 0xc9, 0x26, 0x5b, 0xeb, 0x2e, 0xda, 0x90, 0x64, 0x9d, 0x4d, 0x30, 0x36, 0x08,
	0x21, 0xc2, 0x2c, 0x28, 0xfe, 0xa0, 0x37, 0x73, 0x5a, 0x11, 0x91, 0x8d, 0xb9, 0x78, 0x19, 0x7a,
	0xa7, 0x8b, 0xa1, 0xc3, 0xf4, 0x74, 0x3b, 0xdd, 0x23, 0x78, 0x55, 0xf0, 0xe4, 0xcd, 0xf7, 0xf0,
	0xea, 0xdd, 0x57, 0xf0, 0x15, 0x7c, 0x10, 0xe9, 0x9e, 0x19, 0x37, 0x2b, 0x6e, 0x58, 0x72, 0x9b,
	0xfa, 0xaa, 0xbe, 0xaa, 0xfa, 0xaa, 0xbf, 0x81, 0xdd, 0x54, 0x0b, 0x4c, 0x4c, 0xa9, 0x53, 0xb4,
	0x56, 0x16, 0x59, 0x6c, 0x4a, 0xed, 0x34, 0x1d, 0x5b, 0x2c, 0x3f, 0xc8, 0x14, 0xe3, 0x7f, 0xd3,
	0xdc, 0xc8, 0xe8, 0x20, 0xd3, 0x3a, 0xcb, 0x71, 0xc2, 0x8d, 0x9c, 0xf0, 0xa2, 0xd0, 0x8e, 0x3b,
	0xa9, 0x0b, 0x5b, 0x53, 0xd9, 0x0f, 0x02, 0x83, 0xb3, 0x6a, 0xae, 0xa4, 0x3b, 0xd5, 0x02, 0x67,
	0xf8, 0x9e, 0xee, 0xc3, 0x76, 0x65, 0xb1, 0x4c, 0xa4, 0x18, 0x91, 0x23, 0x72, 0xdc, 0x99, 0x75,
	0x7d, 0x38, 0x15, 0x74, 0x0c, 0xbd, 0x90, 0x28, 0xb8, 0xc2, 0xd1, 0xc6, 0x11, 0x39, 0xee, 0xcd,
	0x76, 0x3c, 0xf0, 0x9a, 0x2b, 0xa4, 0x87, 0x00, 0xa6, 0xd4, 0xf3, 0x1c, 0x95, 0x27, 0x76, 0x02,
	0xb1, 0xd7, 0x20, 0x53, 0x41, 0xef, 0xc2, 0x8d, 0x36, 0x1d, 0xe8, 0x9b, 0x81, 0xde, 0x6f, 0xb0,
	0xd0, 0x21, 0x82, 0x9d, 0x9c, 0x17, 0x59, 0xc5, 0x33, 0x1c, 0x6d, 0xd5, 0xdd, 0xdb, 0x98, 0x52,
	0xd8, 0xf4, 0xd2, 0x46, 0xdd, 0x80, 0x87, 0x6f, 0x76, 0x13, 0x86, 0x97, 0x17, 0xb7, 0x86, 0x15,
	0x10, 0x9d, 0x1b, 0xc1, 0x1d, 0x7a, 0xe4, 0x54, 0x2b, 0x23, 0x73, 0x3c, 0x73, 0xdc, 0x55, 0xb6,
	0xd1, 0x15, 0xce, 0xb3, 0xd0, 0xe5, 0xc3, 0xa9, 0xa0, 0x7b, 0xd0, 0xb5, 0xa1, 0xaa, 0x11, 0xd5,
	0x44, 0xf4, 0x0e, 0xf4, 0xd3, 0xba, 0x49, 0x92, 0xeb, 0x2c, 0x68, 0xea, 0xcd, 0xa0, 0x81, 0x5e,
	0xe9, 0x8c, 0x1d, 0xc2, 0x78, 0xe5, 0x3c, 0x6b, 0xd8, 0x4f, 0x02, 0xa3, 0x45, 0xfe, 0x65, 0x25,
	0xb2, 0x75, 0xb6, 0xb9, 0x07, 0xc3, 0x76, 0xea, 0xd2, 0x56, 0x83, 0xf4, 0xf2, 0x00, 0x7f, 0xd0,
	0x0b, 0xdf, 0xb1, 0x2d, 0xaa, 0xb7, 0xeb, 0x5f, 0x2c, 0xa6, 0x50, 0x06, 0x83, 0xd4, 0x54, 0x89,
	0x93, 0x0a, 0x93, 0xca, 0xa2, 0x68, 0x8f, 0x9e, 0x9a, 0xea, 0xad, 0x54, 0x78, 0x6e, 0x51, 0x78,
	0x8d, 0x0a, 0x95, 0x2e, 0x3f, 0xd6, 0x15, 0xf5, 0xdd, 0xa1, 0x86, 0x7c, 0x01, 0x1b, 0xc3, 0xed,
	0x15, 0x1a, 0xac, 0x79, 0xf0, 0xbd, 0x03, 0x43, 0x8f, 0xbf, 0xf9, 0xeb, 0x38, 0xfa, 0x99, 0x00,
	0x2c, 0x9e, 0x85, 0x9e, 0xc4, 0x57, 0x58, 0x33, 0x5e, 0x32, 0x5e, 0x74, 0x7f, 0xed, 0x5a, 0x6b,
	0xd8, 0xc1, 0xa7, 0x5f, 0xbf, 0xbf, 0x6d, 0xec, 0xb1, 0x5b, 0xc1, 0xd7, 0x8d, 0x8f, 0x26, 0x46,
	0x5b, 0xf7, 0x8c, 0x9c, 0xd0, 0xaf, 0x04, 0xf6, 0x57, 0x3c, 0x0d, 0x7d, 0x72, 0xe5, 0x98, 0xd5,
	0x06, 0x8a, 0x9e, 0x5e, 0x8f, 0x68, 0x0d, 0xfd, 0x42, 0x60, 0xf7, 0xbf, 0x57, 0xa4, 0x8f, 0xd6,
	0xec, 0xb9, 0xec, 0x9e, 0xe8, 0xf1, 0x75, 0x68, 0xd6, 0xbc, 0xd8, 0x7e, 0xb7, 0x15, 0x3f, 0xe7,
	0x46, 0xce, 0xbb, 0xe1, 0xef, 0x7f, 0xf8, 0x27, 0x00, 0x00, 0xff, 0xff, 0x54, 0xfe, 0x41, 0x50,
	0x51, 0x04, 0x00, 0x00,
}
