server:
  http:
    addr: 0.0.0.0:8000
    timeout: 1s
  grpc:
    addr: 0.0.0.0:9003
    timeout: 3s
data:
  database:
    driver: mysql
    source: jiyeon:1234@tcp(127.0.0.1:3307)/Another_Nikki?charset=utf8mb4&parseTime=True&loc=Local
  redis:
    addr: 127.0.0.1:6379
    read_timeout: 0.2s
    write_timeout: 0.2s

