server:
  http:
    addr: 0.0.0.0:8000
    timeout: 1s
  grpc:
    addr: 0.0.0.0:9003
    timeout: 3s
data:
  database:
    driver: mysql
    source: jiyeon:1234@tcp(127.0.0.1:3307)/Another_Nikki?charset=utf8mb4&parseTime=True&loc=Local
  redis:
    addr: 127.0.0.1:6379
    read_timeout: 0.2s
    write_timeout: 0.2s

avatars:
  avatars:
    - https://cdn.acwing.com/media/user/profile/photo/291799_md_6b3fa3b5c2.jpg
    - https://cdn.acwing.com/media/user/profile/photo/280601_md_7c8545f32d.jpg
    - https://cdn.acwing.com/media/user/profile/photo/212592_md_a4da5ddd3f.jpg
    - https://cdn.acwing.com/media/user/profile/photo/242361_md_1587318a52.jpg
    - https://cdn.acwing.com/media/user/profile/photo/282267_md_e887deadb4.jpg
    - https://cdn.acwing.com/media/user/profile/photo/210127_md_9b229bc9b3.jpg
    - https://cdn.acwing.com/media/user/profile/photo/210988_md_15643b620b.jpg
    - https://cdn.acwing.com/media/user/profile/photo/214436_md_7c210e4453.PNG
    - https://cdn.acwing.com/media/user/profile/photo/225147_md_967700a846.jpg
