// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: judge.proto

package api

import (
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type JudgeReq struct {
	Code                 string   `protobuf:"bytes,1,opt,name=Code,json=code,proto3" json:"code"`
	Language             string   `protobuf:"bytes,2,opt,name=Language,json=language,proto3" json:"language"`
	Input                string   `protobuf:"bytes,3,opt,name=Input,json=input,proto3" json:"input"`
	ProblemName          string   `protobuf:"bytes,4,opt,name=ProblemName,json=problem_name,proto3" json:"problem_name"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JudgeReq) Reset()         { *m = JudgeReq{} }
func (m *JudgeReq) String() string { return proto.CompactTextString(m) }
func (*JudgeReq) ProtoMessage()    {}
func (*JudgeReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_a2b4fa635fb2baaa, []int{0}
}
func (m *JudgeReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JudgeReq.Unmarshal(m, b)
}
func (m *JudgeReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JudgeReq.Marshal(b, m, deterministic)
}
func (m *JudgeReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JudgeReq.Merge(m, src)
}
func (m *JudgeReq) XXX_Size() int {
	return xxx_messageInfo_JudgeReq.Size(m)
}
func (m *JudgeReq) XXX_DiscardUnknown() {
	xxx_messageInfo_JudgeReq.DiscardUnknown(m)
}

var xxx_messageInfo_JudgeReq proto.InternalMessageInfo

func (m *JudgeReq) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *JudgeReq) GetLanguage() string {
	if m != nil {
		return m.Language
	}
	return ""
}

func (m *JudgeReq) GetInput() string {
	if m != nil {
		return m.Input
	}
	return ""
}

func (m *JudgeReq) GetProblemName() string {
	if m != nil {
		return m.ProblemName
	}
	return ""
}

type JudgeResp struct {
	CompileState         string   `protobuf:"bytes,1,opt,name=CompileState,json=compile_state,proto3" json:"compile_state"`
	CpuTimeUsed          int64    `protobuf:"varint,2,opt,name=CpuTimeUsed,json=cpu_time_used,proto3" json:"cpu_time_used"`
	MemoryUsed           int64    `protobuf:"varint,3,opt,name=MemoryUsed,json=memory_used,proto3" json:"memory_used"`
	JudgeResult          string   `protobuf:"bytes,4,opt,name=JudgeResult,json=judge_result,proto3" json:"judge_result"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JudgeResp) Reset()         { *m = JudgeResp{} }
func (m *JudgeResp) String() string { return proto.CompactTextString(m) }
func (*JudgeResp) ProtoMessage()    {}
func (*JudgeResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_a2b4fa635fb2baaa, []int{1}
}
func (m *JudgeResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JudgeResp.Unmarshal(m, b)
}
func (m *JudgeResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JudgeResp.Marshal(b, m, deterministic)
}
func (m *JudgeResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JudgeResp.Merge(m, src)
}
func (m *JudgeResp) XXX_Size() int {
	return xxx_messageInfo_JudgeResp.Size(m)
}
func (m *JudgeResp) XXX_DiscardUnknown() {
	xxx_messageInfo_JudgeResp.DiscardUnknown(m)
}

var xxx_messageInfo_JudgeResp proto.InternalMessageInfo

func (m *JudgeResp) GetCompileState() string {
	if m != nil {
		return m.CompileState
	}
	return ""
}

func (m *JudgeResp) GetCpuTimeUsed() int64 {
	if m != nil {
		return m.CpuTimeUsed
	}
	return 0
}

func (m *JudgeResp) GetMemoryUsed() int64 {
	if m != nil {
		return m.MemoryUsed
	}
	return 0
}

func (m *JudgeResp) GetJudgeResult() string {
	if m != nil {
		return m.JudgeResult
	}
	return ""
}

type OnlineRunReq struct {
	Code                 string   `protobuf:"bytes,1,opt,name=Code,json=code,proto3" json:"code"`
	Language             string   `protobuf:"bytes,2,opt,name=Language,json=language,proto3" json:"language"`
	Input                string   `protobuf:"bytes,3,opt,name=Input,json=input,proto3" json:"input"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OnlineRunReq) Reset()         { *m = OnlineRunReq{} }
func (m *OnlineRunReq) String() string { return proto.CompactTextString(m) }
func (*OnlineRunReq) ProtoMessage()    {}
func (*OnlineRunReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_a2b4fa635fb2baaa, []int{2}
}
func (m *OnlineRunReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OnlineRunReq.Unmarshal(m, b)
}
func (m *OnlineRunReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OnlineRunReq.Marshal(b, m, deterministic)
}
func (m *OnlineRunReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OnlineRunReq.Merge(m, src)
}
func (m *OnlineRunReq) XXX_Size() int {
	return xxx_messageInfo_OnlineRunReq.Size(m)
}
func (m *OnlineRunReq) XXX_DiscardUnknown() {
	xxx_messageInfo_OnlineRunReq.DiscardUnknown(m)
}

var xxx_messageInfo_OnlineRunReq proto.InternalMessageInfo

func (m *OnlineRunReq) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *OnlineRunReq) GetLanguage() string {
	if m != nil {
		return m.Language
	}
	return ""
}

func (m *OnlineRunReq) GetInput() string {
	if m != nil {
		return m.Input
	}
	return ""
}

type OnlineRunResp struct {
	CompileState         string   `protobuf:"bytes,1,opt,name=CompileState,json=compile_state,proto3" json:"compile_state"`
	CpuTimeUsed          int64    `protobuf:"varint,2,opt,name=CpuTimeUsed,json=cpu_time_used,proto3" json:"cpu_time_used"`
	MemoryUsed           int64    `protobuf:"varint,3,opt,name=MemoryUsed,json=memory_used,proto3" json:"memory_used"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OnlineRunResp) Reset()         { *m = OnlineRunResp{} }
func (m *OnlineRunResp) String() string { return proto.CompactTextString(m) }
func (*OnlineRunResp) ProtoMessage()    {}
func (*OnlineRunResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_a2b4fa635fb2baaa, []int{3}
}
func (m *OnlineRunResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OnlineRunResp.Unmarshal(m, b)
}
func (m *OnlineRunResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OnlineRunResp.Marshal(b, m, deterministic)
}
func (m *OnlineRunResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OnlineRunResp.Merge(m, src)
}
func (m *OnlineRunResp) XXX_Size() int {
	return xxx_messageInfo_OnlineRunResp.Size(m)
}
func (m *OnlineRunResp) XXX_DiscardUnknown() {
	xxx_messageInfo_OnlineRunResp.DiscardUnknown(m)
}

var xxx_messageInfo_OnlineRunResp proto.InternalMessageInfo

func (m *OnlineRunResp) GetCompileState() string {
	if m != nil {
		return m.CompileState
	}
	return ""
}

func (m *OnlineRunResp) GetCpuTimeUsed() int64 {
	if m != nil {
		return m.CpuTimeUsed
	}
	return 0
}

func (m *OnlineRunResp) GetMemoryUsed() int64 {
	if m != nil {
		return m.MemoryUsed
	}
	return 0
}

func init() {
	proto.RegisterType((*JudgeReq)(nil), "AnotherNikki.oj.judge.JudgeReq")
	proto.RegisterType((*JudgeResp)(nil), "AnotherNikki.oj.judge.JudgeResp")
	proto.RegisterType((*OnlineRunReq)(nil), "AnotherNikki.oj.judge.OnlineRunReq")
	proto.RegisterType((*OnlineRunResp)(nil), "AnotherNikki.oj.judge.OnlineRunResp")
}

func init() { proto.RegisterFile("judge.proto", fileDescriptor_a2b4fa635fb2baaa) }

var fileDescriptor_a2b4fa635fb2baaa = []byte{
	// 410 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xd4, 0x53, 0x4d, 0x8b, 0xd4, 0x40,
	0x10, 0x25, 0xce, 0xcc, 0x92, 0xa9, 0x99, 0x45, 0x6d, 0x10, 0xc2, 0x20, 0xf4, 0x12, 0x3d, 0xec,
	0xc5, 0x8c, 0xb8, 0xe8, 0xc5, 0x93, 0x3b, 0x27, 0x17, 0x5d, 0xa5, 0xfd, 0x38, 0x78, 0x09, 0xc9,
	0xa4, 0xcc, 0xf6, 0x6e, 0x3a, 0xdd, 0x26, 0xdd, 0x88, 0xff, 0x48, 0xf0, 0xe2, 0x2f, 0x0a, 0x78,
	0xcd, 0xaf, 0x90, 0x54, 0x66, 0x96, 0x04, 0xfc, 0xb8, 0x09, 0x5e, 0x92, 0x7e, 0xaf, 0xdf, 0x4b,
	0xaa, 0x5e, 0x75, 0xc3, 0xe2, 0xd2, 0x65, 0x39, 0x46, 0xa6, 0xd2, 0x56, 0xb3, 0x3b, 0xcf, 0x4a,
	0x6d, 0x2f, 0xb0, 0x3a, 0x97, 0x57, 0x57, 0x32, 0xd2, 0x97, 0x11, 0x6d, 0xae, 0x1e, 0xe4, 0xd2,
	0x5e, 0xb8, 0x34, 0xda, 0x6a, 0xb5, 0xce, 0x75, 0xae, 0xd7, 0xa4, 0x4e, 0xdd, 0x47, 0x42, 0x04,
	0x68, 0xd5, 0x7f, 0x25, 0xfc, 0xea, 0x81, 0x7f, 0xd6, 0x19, 0x05, 0x7e, 0x62, 0x77, 0x61, 0xba,
	0xd1, 0x19, 0x06, 0xde, 0x91, 0x77, 0x3c, 0x3f, 0xf5, 0xdb, 0x86, 0x4f, 0xb7, 0x3a, 0x43, 0x41,
	0x4f, 0x76, 0x0c, 0xfe, 0x8b, 0xa4, 0xcc, 0x5d, 0x92, 0x63, 0x70, 0x83, 0x14, 0xcb, 0xb6, 0xe1,
	0x7e, 0xb1, 0xe3, 0xc4, 0xf5, 0x8a, 0x71, 0x98, 0x3d, 0x2f, 0x8d, 0xb3, 0xc1, 0x84, 0x64, 0xf3,
	0xb6, 0xe1, 0x33, 0xd9, 0x11, 0xa2, 0x7f, 0xb1, 0x13, 0x58, 0xbc, 0xae, 0x74, 0x5a, 0xa0, 0x3a,
	0x4f, 0x14, 0x06, 0x53, 0x92, 0xdd, 0x6a, 0x1b, 0xbe, 0x34, 0x3d, 0x1d, 0x97, 0x89, 0x42, 0x31,
	0x42, 0xe1, 0x0f, 0x0f, 0xe6, 0xbb, 0x52, 0x6b, 0xc3, 0x9e, 0xc0, 0x72, 0xa3, 0x95, 0x91, 0x05,
	0xbe, 0xb1, 0x89, 0xdd, 0xd7, 0x7c, 0xbb, 0x6d, 0xf8, 0xe1, 0xb6, 0xe7, 0xe3, 0xba, 0xdb, 0x10,
	0x63, 0xc8, 0x1e, 0xc3, 0x62, 0x63, 0xdc, 0x5b, 0xa9, 0xf0, 0x5d, 0x8d, 0x19, 0x35, 0x32, 0xd9,
	0xd9, 0x8c, 0x8b, 0xad, 0x54, 0x18, 0xbb, 0x1a, 0x33, 0x31, 0x86, 0xec, 0x21, 0xc0, 0x4b, 0x54,
	0xba, 0xfa, 0x42, 0xae, 0x09, 0xb9, 0x6e, 0xb6, 0x0d, 0x5f, 0x28, 0x62, 0x7b, 0xcf, 0x10, 0x74,
	0x3d, 0xee, 0xab, 0x75, 0x85, 0x1d, 0xf6, 0x48, 0x83, 0x8a, 0x2b, 0xe2, 0xc5, 0x08, 0x85, 0x9f,
	0x61, 0xf9, 0xaa, 0x2c, 0x64, 0x89, 0xc2, 0x95, 0xff, 0x72, 0x22, 0xe1, 0x77, 0x0f, 0x0e, 0x07,
	0x7f, 0xfe, 0x0f, 0x02, 0x7e, 0xf4, 0xcd, 0x83, 0x19, 0x85, 0xc7, 0xce, 0x60, 0x46, 0x51, 0x33,
	0x1e, 0xfd, 0xf2, 0x52, 0x44, 0xfb, 0x13, 0xbe, 0x3a, 0xfa, 0xb3, 0xa0, 0x36, 0xec, 0x3d, 0xcc,
	0xaf, 0x73, 0x60, 0xf7, 0x7e, 0x23, 0x1f, 0xce, 0x68, 0x75, 0xff, 0xef, 0xa2, 0xda, 0x9c, 0xfa,
	0x1f, 0x0e, 0xa2, 0xf5, 0xd3, 0xc4, 0xc8, 0xf4, 0x80, 0x6e, 0xde, 0xc9, 0xcf, 0x00, 0x00, 0x00,
	0xff, 0xff, 0xa9, 0xa0, 0xd4, 0x07, 0xce, 0x03, 0x00, 0x00,
}
