// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: judge.proto

package api

import (
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type Language int32

const (
	Language_Cpp    Language = 0
	Language_Python Language = 1
	Language_Java   Language = 2
	Language_Golang Language = 3
)

var Language_name = map[int32]string{
	0: "Cpp",
	1: "Python",
	2: "Java",
	3: "Golang",
}

var Language_value = map[string]int32{
	"Cpp":    0,
	"Python": 1,
	"Java":   2,
	"Golang": 3,
}

func (x Language) String() string {
	return proto.EnumName(Language_name, int32(x))
}

func (Language) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_a2b4fa635fb2baaa, []int{0}
}

type JudgeReq struct {
	Code                 string   `protobuf:"bytes,1,opt,name=Code,json=code,proto3" json:"code"`
	Language             Language `protobuf:"varint,2,opt,name=Language,json=language,proto3,enum=AnotherNikki.oj.judge.Language" json:"language"`
	ProblemName          string   `protobuf:"bytes,3,opt,name=ProblemName,json=problem_name,proto3" json:"problem_name"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JudgeReq) Reset()         { *m = JudgeReq{} }
func (m *JudgeReq) String() string { return proto.CompactTextString(m) }
func (*JudgeReq) ProtoMessage()    {}
func (*JudgeReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_a2b4fa635fb2baaa, []int{0}
}
func (m *JudgeReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JudgeReq.Unmarshal(m, b)
}
func (m *JudgeReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JudgeReq.Marshal(b, m, deterministic)
}
func (m *JudgeReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JudgeReq.Merge(m, src)
}
func (m *JudgeReq) XXX_Size() int {
	return xxx_messageInfo_JudgeReq.Size(m)
}
func (m *JudgeReq) XXX_DiscardUnknown() {
	xxx_messageInfo_JudgeReq.DiscardUnknown(m)
}

var xxx_messageInfo_JudgeReq proto.InternalMessageInfo

func (m *JudgeReq) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *JudgeReq) GetLanguage() Language {
	if m != nil {
		return m.Language
	}
	return Language_Cpp
}

func (m *JudgeReq) GetProblemName() string {
	if m != nil {
		return m.ProblemName
	}
	return ""
}

type JudgeResp struct {
	CompileState         string   `protobuf:"bytes,1,opt,name=CompileState,json=compile_state,proto3" json:"compile_state"`
	CpuTimeUsed          string   `protobuf:"bytes,2,opt,name=CpuTimeUsed,json=cpu_time_used,proto3" json:"cpu_time_used"`
	MemoryUsed           string   `protobuf:"bytes,3,opt,name=MemoryUsed,json=memory_used,proto3" json:"memory_used"`
	JudgeResult          string   `protobuf:"bytes,4,opt,name=JudgeResult,json=judge_result,proto3" json:"judge_result"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JudgeResp) Reset()         { *m = JudgeResp{} }
func (m *JudgeResp) String() string { return proto.CompactTextString(m) }
func (*JudgeResp) ProtoMessage()    {}
func (*JudgeResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_a2b4fa635fb2baaa, []int{1}
}
func (m *JudgeResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JudgeResp.Unmarshal(m, b)
}
func (m *JudgeResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JudgeResp.Marshal(b, m, deterministic)
}
func (m *JudgeResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JudgeResp.Merge(m, src)
}
func (m *JudgeResp) XXX_Size() int {
	return xxx_messageInfo_JudgeResp.Size(m)
}
func (m *JudgeResp) XXX_DiscardUnknown() {
	xxx_messageInfo_JudgeResp.DiscardUnknown(m)
}

var xxx_messageInfo_JudgeResp proto.InternalMessageInfo

func (m *JudgeResp) GetCompileState() string {
	if m != nil {
		return m.CompileState
	}
	return ""
}

func (m *JudgeResp) GetCpuTimeUsed() string {
	if m != nil {
		return m.CpuTimeUsed
	}
	return ""
}

func (m *JudgeResp) GetMemoryUsed() string {
	if m != nil {
		return m.MemoryUsed
	}
	return ""
}

func (m *JudgeResp) GetJudgeResult() string {
	if m != nil {
		return m.JudgeResult
	}
	return ""
}

type OnlineRunReq struct {
	Code                 string   `protobuf:"bytes,1,opt,name=Code,json=code,proto3" json:"code"`
	Language             Language `protobuf:"varint,2,opt,name=Language,json=language,proto3,enum=AnotherNikki.oj.judge.Language" json:"language"`
	Input                string   `protobuf:"bytes,3,opt,name=Input,json=input,proto3" json:"input"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OnlineRunReq) Reset()         { *m = OnlineRunReq{} }
func (m *OnlineRunReq) String() string { return proto.CompactTextString(m) }
func (*OnlineRunReq) ProtoMessage()    {}
func (*OnlineRunReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_a2b4fa635fb2baaa, []int{2}
}
func (m *OnlineRunReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OnlineRunReq.Unmarshal(m, b)
}
func (m *OnlineRunReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OnlineRunReq.Marshal(b, m, deterministic)
}
func (m *OnlineRunReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OnlineRunReq.Merge(m, src)
}
func (m *OnlineRunReq) XXX_Size() int {
	return xxx_messageInfo_OnlineRunReq.Size(m)
}
func (m *OnlineRunReq) XXX_DiscardUnknown() {
	xxx_messageInfo_OnlineRunReq.DiscardUnknown(m)
}

var xxx_messageInfo_OnlineRunReq proto.InternalMessageInfo

func (m *OnlineRunReq) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *OnlineRunReq) GetLanguage() Language {
	if m != nil {
		return m.Language
	}
	return Language_Cpp
}

func (m *OnlineRunReq) GetInput() string {
	if m != nil {
		return m.Input
	}
	return ""
}

type OnlineRunResp struct {
	CompileState         string   `protobuf:"bytes,1,opt,name=CompileState,json=compile_state,proto3" json:"compile_state"`
	CpuTimeUsed          string   `protobuf:"bytes,2,opt,name=CpuTimeUsed,json=cpu_time_used,proto3" json:"cpu_time_used"`
	MemoryUsed           string   `protobuf:"bytes,3,opt,name=MemoryUsed,json=memory_used,proto3" json:"memory_used"`
	Output               string   `protobuf:"bytes,4,opt,name=Output,json=output,proto3" json:"output"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OnlineRunResp) Reset()         { *m = OnlineRunResp{} }
func (m *OnlineRunResp) String() string { return proto.CompactTextString(m) }
func (*OnlineRunResp) ProtoMessage()    {}
func (*OnlineRunResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_a2b4fa635fb2baaa, []int{3}
}
func (m *OnlineRunResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OnlineRunResp.Unmarshal(m, b)
}
func (m *OnlineRunResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OnlineRunResp.Marshal(b, m, deterministic)
}
func (m *OnlineRunResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OnlineRunResp.Merge(m, src)
}
func (m *OnlineRunResp) XXX_Size() int {
	return xxx_messageInfo_OnlineRunResp.Size(m)
}
func (m *OnlineRunResp) XXX_DiscardUnknown() {
	xxx_messageInfo_OnlineRunResp.DiscardUnknown(m)
}

var xxx_messageInfo_OnlineRunResp proto.InternalMessageInfo

func (m *OnlineRunResp) GetCompileState() string {
	if m != nil {
		return m.CompileState
	}
	return ""
}

func (m *OnlineRunResp) GetCpuTimeUsed() string {
	if m != nil {
		return m.CpuTimeUsed
	}
	return ""
}

func (m *OnlineRunResp) GetMemoryUsed() string {
	if m != nil {
		return m.MemoryUsed
	}
	return ""
}

func (m *OnlineRunResp) GetOutput() string {
	if m != nil {
		return m.Output
	}
	return ""
}

func init() {
	proto.RegisterEnum("AnotherNikki.oj.judge.Language", Language_name, Language_value)
	proto.RegisterType((*JudgeReq)(nil), "AnotherNikki.oj.judge.JudgeReq")
	proto.RegisterType((*JudgeResp)(nil), "AnotherNikki.oj.judge.JudgeResp")
	proto.RegisterType((*OnlineRunReq)(nil), "AnotherNikki.oj.judge.OnlineRunReq")
	proto.RegisterType((*OnlineRunResp)(nil), "AnotherNikki.oj.judge.OnlineRunResp")
}

func init() { proto.RegisterFile("judge.proto", fileDescriptor_a2b4fa635fb2baaa) }

var fileDescriptor_a2b4fa635fb2baaa = []byte{
	// 473 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xd4, 0x53, 0x4f, 0x6f, 0xd3, 0x3e,
	0x18, 0xfe, 0x79, 0x6d, 0xf3, 0x4b, 0xdf, 0x76, 0x10, 0x2c, 0x21, 0x55, 0x15, 0x92, 0xab, 0xc0,
	0x61, 0x42, 0x22, 0x45, 0x9b, 0xc6, 0x85, 0x13, 0xed, 0x01, 0xad, 0x82, 0x6d, 0x32, 0x7f, 0x0e,
	0x5c, 0xa2, 0xb4, 0x31, 0xa9, 0xb7, 0x38, 0x36, 0x89, 0x8d, 0xb4, 0x6f, 0xc2, 0x47, 0x40, 0xe2,
	0xeb, 0x70, 0x8e, 0xc4, 0x35, 0x9f, 0x02, 0xc5, 0x69, 0xb6, 0x56, 0x62, 0x70, 0x43, 0xe2, 0x12,
	0xfb, 0x79, 0xfc, 0xbe, 0xc9, 0xf3, 0x3c, 0x6f, 0x0c, 0x83, 0x0b, 0x13, 0x27, 0x2c, 0x50, 0xb9,
	0xd4, 0x12, 0xdf, 0x7f, 0x91, 0x49, 0xbd, 0x66, 0xf9, 0x29, 0xbf, 0xbc, 0xe4, 0x81, 0xbc, 0x08,
	0xec, 0xe1, 0xf8, 0x49, 0xc2, 0xf5, 0xda, 0x2c, 0x83, 0x95, 0x14, 0xd3, 0x44, 0x26, 0x72, 0x6a,
	0xab, 0x97, 0xe6, 0xa3, 0x45, 0x16, 0xd8, 0x5d, 0xf3, 0x16, 0xff, 0x2b, 0x02, 0x77, 0x51, 0x37,
	0x52, 0xf6, 0x09, 0x3f, 0x80, 0xee, 0x5c, 0xc6, 0x6c, 0x84, 0x26, 0xe8, 0xa0, 0x3f, 0x73, 0xab,
	0x92, 0x74, 0x57, 0x32, 0x66, 0xd4, 0x3e, 0xf1, 0x09, 0xb8, 0xaf, 0xa2, 0x2c, 0x31, 0x51, 0xc2,
	0x46, 0x7b, 0x13, 0x74, 0x70, 0xe7, 0x90, 0x04, 0xbf, 0xd4, 0x10, 0xb4, 0x65, 0xb3, 0x61, 0x55,
	0x12, 0x37, 0xdd, 0x20, 0x7a, 0xbd, 0xc3, 0x47, 0x30, 0x38, 0xcf, 0xe5, 0x32, 0x65, 0xe2, 0x34,
	0x12, 0x6c, 0xd4, 0xb1, 0xdf, 0xf3, 0xaa, 0x92, 0x0c, 0x55, 0x43, 0x87, 0x59, 0x24, 0x18, 0xdd,
	0x41, 0xfe, 0x0f, 0x04, 0xfd, 0x8d, 0xd4, 0x42, 0xe1, 0x67, 0x30, 0x9c, 0x4b, 0xa1, 0x78, 0xca,
	0xde, 0xe8, 0x48, 0xb7, 0x9a, 0xef, 0x55, 0x25, 0xd9, 0x5f, 0x35, 0x7c, 0x58, 0xd4, 0x07, 0x74,
	0x17, 0xe2, 0x63, 0x18, 0xcc, 0x95, 0x79, 0xcb, 0x05, 0x7b, 0x57, 0xb0, 0xd8, 0x1a, 0x69, 0xdb,
	0x94, 0x09, 0x35, 0x17, 0x2c, 0x34, 0x05, 0x8b, 0xe9, 0x2e, 0xc4, 0x4f, 0x01, 0x5e, 0x33, 0x21,
	0xf3, 0x2b, 0xdb, 0xd5, 0x08, 0xbe, 0x5b, 0x95, 0x64, 0x20, 0x2c, 0xdb, 0xf4, 0x6c, 0x83, 0xda,
	0x63, 0xab, 0xd6, 0xa4, 0x7a, 0xd4, 0xbd, 0xf1, 0x68, 0x43, 0x0a, 0x73, 0xcb, 0xd3, 0x1d, 0xe4,
	0x7f, 0x41, 0x30, 0x3c, 0xcb, 0x52, 0x9e, 0x31, 0x6a, 0xb2, 0xbf, 0x3a, 0x12, 0x02, 0xbd, 0x93,
	0x4c, 0x19, 0xbd, 0xf1, 0xd6, 0xaf, 0x4a, 0xd2, 0xe3, 0x35, 0x41, 0x9b, 0xc5, 0xff, 0x8e, 0x60,
	0x7f, 0x4b, 0xda, 0xbf, 0x30, 0x02, 0x1f, 0x9c, 0x33, 0xa3, 0x6b, 0x53, 0x4d, 0xfa, 0x50, 0x95,
	0xc4, 0x91, 0x96, 0xa1, 0x9b, 0xf5, 0xf1, 0xf1, 0x4d, 0x84, 0xf8, 0x7f, 0xe8, 0xcc, 0x95, 0xf2,
	0xfe, 0xc3, 0x00, 0xce, 0xf9, 0x95, 0x5e, 0xcb, 0xcc, 0x43, 0xd8, 0x85, 0xee, 0x22, 0xfa, 0x1c,
	0x79, 0x7b, 0x35, 0xfb, 0x52, 0xd6, 0x81, 0x79, 0x9d, 0xc3, 0x6f, 0x08, 0x7a, 0x76, 0xbc, 0x78,
	0xd1, 0x6e, 0x6e, 0x8b, 0xbe, 0xbd, 0x5e, 0xe3, 0xc9, 0xef, 0x0b, 0x0a, 0x85, 0xdf, 0x43, 0xff,
	0x3a, 0x62, 0xfc, 0xf0, 0x96, 0xf2, 0xed, 0xff, 0x63, 0xfc, 0xe8, 0xcf, 0x45, 0x85, 0x9a, 0xb9,
	0x1f, 0x9c, 0x60, 0xfa, 0x3c, 0x52, 0x7c, 0xe9, 0xd8, 0x6b, 0x7f, 0xf4, 0x33, 0x00, 0x00, 0xff,
	0xff, 0xd9, 0x71, 0xfb, 0xaf, 0x4b, 0x04, 0x00, 0x00,
}
