// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"Another-Nikki/code_processing/service/internal/conf"
	"Another-Nikki/code_processing/service/internal/data"
	"Another-Nikki/code_processing/service/internal/server"
	"Another-Nikki/code_processing/service/internal/service"
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	discovery := data.NewDiscovery()
	globalGrpcClient := data.NewGlobalGrpcClient(confData, discovery)
	dataData, cleanup, err := data.NewData(confData, logger, globalGrpcClient)
	if err != nil {
		return nil, nil, err
	}
	codeProcessingService := service.NewCodeProcessingService(dataData)
	grpcServer := server.NewGRPCServer(confServer, codeProcessingService, logger)
	registrar := data.NewRegistry()
	app := newApp(logger, grpcServer, registrar)
	return app, func() {
		cleanup()
	}, nil
}
