// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"Another-Nikki/code_processing/service/internal/conf"
	"Another-Nikki/code_processing/service/internal/server"
	"Another-Nikki/code_processing/service/internal/service"
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, data *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	codeProcessingService := service.NewCodeProcessingService()
	grpcServer := server.NewGRPCServer(confServer, codeProcessingService, logger)
	app := newApp(logger, grpcServer)
	return app, func() {
	}, nil
}
