version: '3'
services:
  mysql:
    image: mysql:latest
    container_name: mysql
    ports:
      - "3307:3306"       #后者是docker中的端口
    environment:
      - MYSQL_DATABASE=Another_Nikki
      - MYSQL_USER=jiyeon
      - MYSQL_PASSWORD=1234
      - MYSQL_ROOT_PASSWORD=1234

  canal-server:
    image: canal/canal-server
    container_name: canal-server
    ports:
      - 11111:11111
    environment:
      - canal.instance.master.address=mysql:3306
      - canal.instance.dbUsername=root
      - canal.instance.dbPassword=1234
    volumes:
      - $PWD/canal/conf/:/home/admin/canal-server/conf/
      - $PWD/canal/logs/:/home/admin/canal-server/logs/
    depends_on:
      - mysql

