// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: interact_hub.proto

package api

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type PostProblemReq struct {
	ProblemId            int64    `protobuf:"varint,1,opt,name=problem_id,json=problemId,proto3" json:"problem_id,omitempty"`
	ProblemTitle         string   `protobuf:"bytes,2,opt,name=problem_title,json=problemTitle,proto3" json:"problem_title,omitempty"`
	ProblemDescription   string   `protobuf:"bytes,3,opt,name=problem_description,json=problemDescription,proto3" json:"problem_description,omitempty"`
	ProblemContent       string   `protobuf:"bytes,4,opt,name=problem_content,json=problemContent,proto3" json:"problem_content,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PostProblemReq) Reset()         { *m = PostProblemReq{} }
func (m *PostProblemReq) String() string { return proto.CompactTextString(m) }
func (*PostProblemReq) ProtoMessage()    {}
func (*PostProblemReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_53b9a3b79039de3a, []int{0}
}
func (m *PostProblemReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PostProblemReq.Unmarshal(m, b)
}
func (m *PostProblemReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PostProblemReq.Marshal(b, m, deterministic)
}
func (m *PostProblemReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PostProblemReq.Merge(m, src)
}
func (m *PostProblemReq) XXX_Size() int {
	return xxx_messageInfo_PostProblemReq.Size(m)
}
func (m *PostProblemReq) XXX_DiscardUnknown() {
	xxx_messageInfo_PostProblemReq.DiscardUnknown(m)
}

var xxx_messageInfo_PostProblemReq proto.InternalMessageInfo

func (m *PostProblemReq) GetProblemId() int64 {
	if m != nil {
		return m.ProblemId
	}
	return 0
}

func (m *PostProblemReq) GetProblemTitle() string {
	if m != nil {
		return m.ProblemTitle
	}
	return ""
}

func (m *PostProblemReq) GetProblemDescription() string {
	if m != nil {
		return m.ProblemDescription
	}
	return ""
}

func (m *PostProblemReq) GetProblemContent() string {
	if m != nil {
		return m.ProblemContent
	}
	return ""
}

type PostProblemResp struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PostProblemResp) Reset()         { *m = PostProblemResp{} }
func (m *PostProblemResp) String() string { return proto.CompactTextString(m) }
func (*PostProblemResp) ProtoMessage()    {}
func (*PostProblemResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_53b9a3b79039de3a, []int{1}
}
func (m *PostProblemResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PostProblemResp.Unmarshal(m, b)
}
func (m *PostProblemResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PostProblemResp.Marshal(b, m, deterministic)
}
func (m *PostProblemResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PostProblemResp.Merge(m, src)
}
func (m *PostProblemResp) XXX_Size() int {
	return xxx_messageInfo_PostProblemResp.Size(m)
}
func (m *PostProblemResp) XXX_DiscardUnknown() {
	xxx_messageInfo_PostProblemResp.DiscardUnknown(m)
}

var xxx_messageInfo_PostProblemResp proto.InternalMessageInfo

type GetProblemByIdReq struct {
	ProblemId            int64    `protobuf:"varint,1,opt,name=problem_id,json=problemId,proto3" json:"problem_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetProblemByIdReq) Reset()         { *m = GetProblemByIdReq{} }
func (m *GetProblemByIdReq) String() string { return proto.CompactTextString(m) }
func (*GetProblemByIdReq) ProtoMessage()    {}
func (*GetProblemByIdReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_53b9a3b79039de3a, []int{2}
}
func (m *GetProblemByIdReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetProblemByIdReq.Unmarshal(m, b)
}
func (m *GetProblemByIdReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetProblemByIdReq.Marshal(b, m, deterministic)
}
func (m *GetProblemByIdReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetProblemByIdReq.Merge(m, src)
}
func (m *GetProblemByIdReq) XXX_Size() int {
	return xxx_messageInfo_GetProblemByIdReq.Size(m)
}
func (m *GetProblemByIdReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetProblemByIdReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetProblemByIdReq proto.InternalMessageInfo

func (m *GetProblemByIdReq) GetProblemId() int64 {
	if m != nil {
		return m.ProblemId
	}
	return 0
}

type GetProblemByIdResp struct {
	ProblemTitle         string   `protobuf:"bytes,1,opt,name=problem_title,json=problemTitle,proto3" json:"problem_title,omitempty"`
	ProblemDescription   string   `protobuf:"bytes,2,opt,name=problem_description,json=problemDescription,proto3" json:"problem_description,omitempty"`
	ProblemContent       string   `protobuf:"bytes,3,opt,name=problem_content,json=problemContent,proto3" json:"problem_content,omitempty"`
	CreatedTime          string   `protobuf:"bytes,4,opt,name=created_time,json=createdTime,proto3" json:"created_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetProblemByIdResp) Reset()         { *m = GetProblemByIdResp{} }
func (m *GetProblemByIdResp) String() string { return proto.CompactTextString(m) }
func (*GetProblemByIdResp) ProtoMessage()    {}
func (*GetProblemByIdResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_53b9a3b79039de3a, []int{3}
}
func (m *GetProblemByIdResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetProblemByIdResp.Unmarshal(m, b)
}
func (m *GetProblemByIdResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetProblemByIdResp.Marshal(b, m, deterministic)
}
func (m *GetProblemByIdResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetProblemByIdResp.Merge(m, src)
}
func (m *GetProblemByIdResp) XXX_Size() int {
	return xxx_messageInfo_GetProblemByIdResp.Size(m)
}
func (m *GetProblemByIdResp) XXX_DiscardUnknown() {
	xxx_messageInfo_GetProblemByIdResp.DiscardUnknown(m)
}

var xxx_messageInfo_GetProblemByIdResp proto.InternalMessageInfo

func (m *GetProblemByIdResp) GetProblemTitle() string {
	if m != nil {
		return m.ProblemTitle
	}
	return ""
}

func (m *GetProblemByIdResp) GetProblemDescription() string {
	if m != nil {
		return m.ProblemDescription
	}
	return ""
}

func (m *GetProblemByIdResp) GetProblemContent() string {
	if m != nil {
		return m.ProblemContent
	}
	return ""
}

func (m *GetProblemByIdResp) GetCreatedTime() string {
	if m != nil {
		return m.CreatedTime
	}
	return ""
}

type GetProblemByPageReq struct {
	PageNum              int64    `protobuf:"varint,1,opt,name=page_num,json=pageNum,proto3" json:"page_num,omitempty"`
	PageSize             int64    `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetProblemByPageReq) Reset()         { *m = GetProblemByPageReq{} }
func (m *GetProblemByPageReq) String() string { return proto.CompactTextString(m) }
func (*GetProblemByPageReq) ProtoMessage()    {}
func (*GetProblemByPageReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_53b9a3b79039de3a, []int{4}
}
func (m *GetProblemByPageReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetProblemByPageReq.Unmarshal(m, b)
}
func (m *GetProblemByPageReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetProblemByPageReq.Marshal(b, m, deterministic)
}
func (m *GetProblemByPageReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetProblemByPageReq.Merge(m, src)
}
func (m *GetProblemByPageReq) XXX_Size() int {
	return xxx_messageInfo_GetProblemByPageReq.Size(m)
}
func (m *GetProblemByPageReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetProblemByPageReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetProblemByPageReq proto.InternalMessageInfo

func (m *GetProblemByPageReq) GetPageNum() int64 {
	if m != nil {
		return m.PageNum
	}
	return 0
}

func (m *GetProblemByPageReq) GetPageSize() int64 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

type ProblemPageDetail struct {
	ProblemId            int64    `protobuf:"varint,1,opt,name=problem_id,json=problemId,proto3" json:"problem_id,omitempty"`
	ProblemTitle         string   `protobuf:"bytes,2,opt,name=problem_title,json=problemTitle,proto3" json:"problem_title,omitempty"`
	CreatedTime          string   `protobuf:"bytes,3,opt,name=created_time,json=createdTime,proto3" json:"created_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProblemPageDetail) Reset()         { *m = ProblemPageDetail{} }
func (m *ProblemPageDetail) String() string { return proto.CompactTextString(m) }
func (*ProblemPageDetail) ProtoMessage()    {}
func (*ProblemPageDetail) Descriptor() ([]byte, []int) {
	return fileDescriptor_53b9a3b79039de3a, []int{5}
}
func (m *ProblemPageDetail) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProblemPageDetail.Unmarshal(m, b)
}
func (m *ProblemPageDetail) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProblemPageDetail.Marshal(b, m, deterministic)
}
func (m *ProblemPageDetail) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProblemPageDetail.Merge(m, src)
}
func (m *ProblemPageDetail) XXX_Size() int {
	return xxx_messageInfo_ProblemPageDetail.Size(m)
}
func (m *ProblemPageDetail) XXX_DiscardUnknown() {
	xxx_messageInfo_ProblemPageDetail.DiscardUnknown(m)
}

var xxx_messageInfo_ProblemPageDetail proto.InternalMessageInfo

func (m *ProblemPageDetail) GetProblemId() int64 {
	if m != nil {
		return m.ProblemId
	}
	return 0
}

func (m *ProblemPageDetail) GetProblemTitle() string {
	if m != nil {
		return m.ProblemTitle
	}
	return ""
}

func (m *ProblemPageDetail) GetCreatedTime() string {
	if m != nil {
		return m.CreatedTime
	}
	return ""
}

type GetProblemByPageResp struct {
	Problems             []*ProblemPageDetail `protobuf:"bytes,1,rep,name=problems,proto3" json:"problems,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *GetProblemByPageResp) Reset()         { *m = GetProblemByPageResp{} }
func (m *GetProblemByPageResp) String() string { return proto.CompactTextString(m) }
func (*GetProblemByPageResp) ProtoMessage()    {}
func (*GetProblemByPageResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_53b9a3b79039de3a, []int{6}
}
func (m *GetProblemByPageResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetProblemByPageResp.Unmarshal(m, b)
}
func (m *GetProblemByPageResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetProblemByPageResp.Marshal(b, m, deterministic)
}
func (m *GetProblemByPageResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetProblemByPageResp.Merge(m, src)
}
func (m *GetProblemByPageResp) XXX_Size() int {
	return xxx_messageInfo_GetProblemByPageResp.Size(m)
}
func (m *GetProblemByPageResp) XXX_DiscardUnknown() {
	xxx_messageInfo_GetProblemByPageResp.DiscardUnknown(m)
}

var xxx_messageInfo_GetProblemByPageResp proto.InternalMessageInfo

func (m *GetProblemByPageResp) GetProblems() []*ProblemPageDetail {
	if m != nil {
		return m.Problems
	}
	return nil
}

type PostArticleReq struct {
	ArticleId            int64    `protobuf:"varint,1,opt,name=article_id,json=articleId,proto3" json:"article_id,omitempty"`
	ArticleTitle         string   `protobuf:"bytes,2,opt,name=article_title,json=articleTitle,proto3" json:"article_title,omitempty"`
	ArticleDescription   string   `protobuf:"bytes,3,opt,name=article_description,json=articleDescription,proto3" json:"article_description,omitempty"`
	ArticleContent       string   `protobuf:"bytes,4,opt,name=article_content,json=articleContent,proto3" json:"article_content,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PostArticleReq) Reset()         { *m = PostArticleReq{} }
func (m *PostArticleReq) String() string { return proto.CompactTextString(m) }
func (*PostArticleReq) ProtoMessage()    {}
func (*PostArticleReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_53b9a3b79039de3a, []int{7}
}
func (m *PostArticleReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PostArticleReq.Unmarshal(m, b)
}
func (m *PostArticleReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PostArticleReq.Marshal(b, m, deterministic)
}
func (m *PostArticleReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PostArticleReq.Merge(m, src)
}
func (m *PostArticleReq) XXX_Size() int {
	return xxx_messageInfo_PostArticleReq.Size(m)
}
func (m *PostArticleReq) XXX_DiscardUnknown() {
	xxx_messageInfo_PostArticleReq.DiscardUnknown(m)
}

var xxx_messageInfo_PostArticleReq proto.InternalMessageInfo

func (m *PostArticleReq) GetArticleId() int64 {
	if m != nil {
		return m.ArticleId
	}
	return 0
}

func (m *PostArticleReq) GetArticleTitle() string {
	if m != nil {
		return m.ArticleTitle
	}
	return ""
}

func (m *PostArticleReq) GetArticleDescription() string {
	if m != nil {
		return m.ArticleDescription
	}
	return ""
}

func (m *PostArticleReq) GetArticleContent() string {
	if m != nil {
		return m.ArticleContent
	}
	return ""
}

type PostArticleResp struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PostArticleResp) Reset()         { *m = PostArticleResp{} }
func (m *PostArticleResp) String() string { return proto.CompactTextString(m) }
func (*PostArticleResp) ProtoMessage()    {}
func (*PostArticleResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_53b9a3b79039de3a, []int{8}
}
func (m *PostArticleResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PostArticleResp.Unmarshal(m, b)
}
func (m *PostArticleResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PostArticleResp.Marshal(b, m, deterministic)
}
func (m *PostArticleResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PostArticleResp.Merge(m, src)
}
func (m *PostArticleResp) XXX_Size() int {
	return xxx_messageInfo_PostArticleResp.Size(m)
}
func (m *PostArticleResp) XXX_DiscardUnknown() {
	xxx_messageInfo_PostArticleResp.DiscardUnknown(m)
}

var xxx_messageInfo_PostArticleResp proto.InternalMessageInfo

type GetArticleByIdReq struct {
	ArticleId            int64    `protobuf:"varint,1,opt,name=article_id,json=articleId,proto3" json:"article_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetArticleByIdReq) Reset()         { *m = GetArticleByIdReq{} }
func (m *GetArticleByIdReq) String() string { return proto.CompactTextString(m) }
func (*GetArticleByIdReq) ProtoMessage()    {}
func (*GetArticleByIdReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_53b9a3b79039de3a, []int{9}
}
func (m *GetArticleByIdReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetArticleByIdReq.Unmarshal(m, b)
}
func (m *GetArticleByIdReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetArticleByIdReq.Marshal(b, m, deterministic)
}
func (m *GetArticleByIdReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetArticleByIdReq.Merge(m, src)
}
func (m *GetArticleByIdReq) XXX_Size() int {
	return xxx_messageInfo_GetArticleByIdReq.Size(m)
}
func (m *GetArticleByIdReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetArticleByIdReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetArticleByIdReq proto.InternalMessageInfo

func (m *GetArticleByIdReq) GetArticleId() int64 {
	if m != nil {
		return m.ArticleId
	}
	return 0
}

type GetArticleByIdResp struct {
	ArticleTitle         string   `protobuf:"bytes,1,opt,name=article_title,json=articleTitle,proto3" json:"article_title,omitempty"`
	ArticleDescription   string   `protobuf:"bytes,2,opt,name=article_description,json=articleDescription,proto3" json:"article_description,omitempty"`
	ArticleContent       string   `protobuf:"bytes,3,opt,name=article_content,json=articleContent,proto3" json:"article_content,omitempty"`
	CreatedTime          string   `protobuf:"bytes,4,opt,name=created_time,json=createdTime,proto3" json:"created_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetArticleByIdResp) Reset()         { *m = GetArticleByIdResp{} }
func (m *GetArticleByIdResp) String() string { return proto.CompactTextString(m) }
func (*GetArticleByIdResp) ProtoMessage()    {}
func (*GetArticleByIdResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_53b9a3b79039de3a, []int{10}
}
func (m *GetArticleByIdResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetArticleByIdResp.Unmarshal(m, b)
}
func (m *GetArticleByIdResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetArticleByIdResp.Marshal(b, m, deterministic)
}
func (m *GetArticleByIdResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetArticleByIdResp.Merge(m, src)
}
func (m *GetArticleByIdResp) XXX_Size() int {
	return xxx_messageInfo_GetArticleByIdResp.Size(m)
}
func (m *GetArticleByIdResp) XXX_DiscardUnknown() {
	xxx_messageInfo_GetArticleByIdResp.DiscardUnknown(m)
}

var xxx_messageInfo_GetArticleByIdResp proto.InternalMessageInfo

func (m *GetArticleByIdResp) GetArticleTitle() string {
	if m != nil {
		return m.ArticleTitle
	}
	return ""
}

func (m *GetArticleByIdResp) GetArticleDescription() string {
	if m != nil {
		return m.ArticleDescription
	}
	return ""
}

func (m *GetArticleByIdResp) GetArticleContent() string {
	if m != nil {
		return m.ArticleContent
	}
	return ""
}

func (m *GetArticleByIdResp) GetCreatedTime() string {
	if m != nil {
		return m.CreatedTime
	}
	return ""
}

type GetArticleByPageReq struct {
	PageNum              int64    `protobuf:"varint,1,opt,name=page_num,json=pageNum,proto3" json:"page_num,omitempty"`
	PageSize             int64    `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetArticleByPageReq) Reset()         { *m = GetArticleByPageReq{} }
func (m *GetArticleByPageReq) String() string { return proto.CompactTextString(m) }
func (*GetArticleByPageReq) ProtoMessage()    {}
func (*GetArticleByPageReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_53b9a3b79039de3a, []int{11}
}
func (m *GetArticleByPageReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetArticleByPageReq.Unmarshal(m, b)
}
func (m *GetArticleByPageReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetArticleByPageReq.Marshal(b, m, deterministic)
}
func (m *GetArticleByPageReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetArticleByPageReq.Merge(m, src)
}
func (m *GetArticleByPageReq) XXX_Size() int {
	return xxx_messageInfo_GetArticleByPageReq.Size(m)
}
func (m *GetArticleByPageReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetArticleByPageReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetArticleByPageReq proto.InternalMessageInfo

func (m *GetArticleByPageReq) GetPageNum() int64 {
	if m != nil {
		return m.PageNum
	}
	return 0
}

func (m *GetArticleByPageReq) GetPageSize() int64 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

type ArticlePageDetail struct {
	ArticleId            int64    `protobuf:"varint,1,opt,name=article_id,json=articleId,proto3" json:"article_id,omitempty"`
	ArticleTitle         string   `protobuf:"bytes,2,opt,name=article_title,json=articleTitle,proto3" json:"article_title,omitempty"`
	CreatedTime          string   `protobuf:"bytes,3,opt,name=created_time,json=createdTime,proto3" json:"created_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ArticlePageDetail) Reset()         { *m = ArticlePageDetail{} }
func (m *ArticlePageDetail) String() string { return proto.CompactTextString(m) }
func (*ArticlePageDetail) ProtoMessage()    {}
func (*ArticlePageDetail) Descriptor() ([]byte, []int) {
	return fileDescriptor_53b9a3b79039de3a, []int{12}
}
func (m *ArticlePageDetail) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ArticlePageDetail.Unmarshal(m, b)
}
func (m *ArticlePageDetail) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ArticlePageDetail.Marshal(b, m, deterministic)
}
func (m *ArticlePageDetail) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ArticlePageDetail.Merge(m, src)
}
func (m *ArticlePageDetail) XXX_Size() int {
	return xxx_messageInfo_ArticlePageDetail.Size(m)
}
func (m *ArticlePageDetail) XXX_DiscardUnknown() {
	xxx_messageInfo_ArticlePageDetail.DiscardUnknown(m)
}

var xxx_messageInfo_ArticlePageDetail proto.InternalMessageInfo

func (m *ArticlePageDetail) GetArticleId() int64 {
	if m != nil {
		return m.ArticleId
	}
	return 0
}

func (m *ArticlePageDetail) GetArticleTitle() string {
	if m != nil {
		return m.ArticleTitle
	}
	return ""
}

func (m *ArticlePageDetail) GetCreatedTime() string {
	if m != nil {
		return m.CreatedTime
	}
	return ""
}

type GetArticleByPageResp struct {
	Articles             []*ArticlePageDetail `protobuf:"bytes,1,rep,name=articles,proto3" json:"articles,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *GetArticleByPageResp) Reset()         { *m = GetArticleByPageResp{} }
func (m *GetArticleByPageResp) String() string { return proto.CompactTextString(m) }
func (*GetArticleByPageResp) ProtoMessage()    {}
func (*GetArticleByPageResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_53b9a3b79039de3a, []int{13}
}
func (m *GetArticleByPageResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetArticleByPageResp.Unmarshal(m, b)
}
func (m *GetArticleByPageResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetArticleByPageResp.Marshal(b, m, deterministic)
}
func (m *GetArticleByPageResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetArticleByPageResp.Merge(m, src)
}
func (m *GetArticleByPageResp) XXX_Size() int {
	return xxx_messageInfo_GetArticleByPageResp.Size(m)
}
func (m *GetArticleByPageResp) XXX_DiscardUnknown() {
	xxx_messageInfo_GetArticleByPageResp.DiscardUnknown(m)
}

var xxx_messageInfo_GetArticleByPageResp proto.InternalMessageInfo

func (m *GetArticleByPageResp) GetArticles() []*ArticlePageDetail {
	if m != nil {
		return m.Articles
	}
	return nil
}

type LoginReq struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginReq) Reset()         { *m = LoginReq{} }
func (m *LoginReq) String() string { return proto.CompactTextString(m) }
func (*LoginReq) ProtoMessage()    {}
func (*LoginReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_53b9a3b79039de3a, []int{14}
}
func (m *LoginReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginReq.Unmarshal(m, b)
}
func (m *LoginReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginReq.Marshal(b, m, deterministic)
}
func (m *LoginReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginReq.Merge(m, src)
}
func (m *LoginReq) XXX_Size() int {
	return xxx_messageInfo_LoginReq.Size(m)
}
func (m *LoginReq) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginReq.DiscardUnknown(m)
}

var xxx_messageInfo_LoginReq proto.InternalMessageInfo

func (m *LoginReq) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *LoginReq) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type LoginResp struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Username             string   `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	UserId               int64    `protobuf:"varint,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Avatar               string   `protobuf:"bytes,4,opt,name=avatar,proto3" json:"avatar,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginResp) Reset()         { *m = LoginResp{} }
func (m *LoginResp) String() string { return proto.CompactTextString(m) }
func (*LoginResp) ProtoMessage()    {}
func (*LoginResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_53b9a3b79039de3a, []int{15}
}
func (m *LoginResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginResp.Unmarshal(m, b)
}
func (m *LoginResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginResp.Marshal(b, m, deterministic)
}
func (m *LoginResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginResp.Merge(m, src)
}
func (m *LoginResp) XXX_Size() int {
	return xxx_messageInfo_LoginResp.Size(m)
}
func (m *LoginResp) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginResp.DiscardUnknown(m)
}

var xxx_messageInfo_LoginResp proto.InternalMessageInfo

func (m *LoginResp) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *LoginResp) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *LoginResp) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *LoginResp) GetAvatar() string {
	if m != nil {
		return m.Avatar
	}
	return ""
}

type RegisterReq struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	ConfirmPassword      string   `protobuf:"bytes,3,opt,name=confirm_password,json=confirmPassword,proto3" json:"confirm_password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterReq) Reset()         { *m = RegisterReq{} }
func (m *RegisterReq) String() string { return proto.CompactTextString(m) }
func (*RegisterReq) ProtoMessage()    {}
func (*RegisterReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_53b9a3b79039de3a, []int{16}
}
func (m *RegisterReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterReq.Unmarshal(m, b)
}
func (m *RegisterReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterReq.Marshal(b, m, deterministic)
}
func (m *RegisterReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterReq.Merge(m, src)
}
func (m *RegisterReq) XXX_Size() int {
	return xxx_messageInfo_RegisterReq.Size(m)
}
func (m *RegisterReq) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterReq.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterReq proto.InternalMessageInfo

func (m *RegisterReq) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *RegisterReq) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *RegisterReq) GetConfirmPassword() string {
	if m != nil {
		return m.ConfirmPassword
	}
	return ""
}

type RegisterResp struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Username             string   `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	UserId               int64    `protobuf:"varint,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterResp) Reset()         { *m = RegisterResp{} }
func (m *RegisterResp) String() string { return proto.CompactTextString(m) }
func (*RegisterResp) ProtoMessage()    {}
func (*RegisterResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_53b9a3b79039de3a, []int{17}
}
func (m *RegisterResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterResp.Unmarshal(m, b)
}
func (m *RegisterResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterResp.Marshal(b, m, deterministic)
}
func (m *RegisterResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterResp.Merge(m, src)
}
func (m *RegisterResp) XXX_Size() int {
	return xxx_messageInfo_RegisterResp.Size(m)
}
func (m *RegisterResp) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterResp.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterResp proto.InternalMessageInfo

func (m *RegisterResp) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *RegisterResp) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *RegisterResp) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

type GetUserByUserNameReq struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserByUserNameReq) Reset()         { *m = GetUserByUserNameReq{} }
func (m *GetUserByUserNameReq) String() string { return proto.CompactTextString(m) }
func (*GetUserByUserNameReq) ProtoMessage()    {}
func (*GetUserByUserNameReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_53b9a3b79039de3a, []int{18}
}
func (m *GetUserByUserNameReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserByUserNameReq.Unmarshal(m, b)
}
func (m *GetUserByUserNameReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserByUserNameReq.Marshal(b, m, deterministic)
}
func (m *GetUserByUserNameReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserByUserNameReq.Merge(m, src)
}
func (m *GetUserByUserNameReq) XXX_Size() int {
	return xxx_messageInfo_GetUserByUserNameReq.Size(m)
}
func (m *GetUserByUserNameReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserByUserNameReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserByUserNameReq proto.InternalMessageInfo

func (m *GetUserByUserNameReq) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

type GetUserByUserNameResp struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Avatar               string   `protobuf:"bytes,2,opt,name=avatar,proto3" json:"avatar,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserByUserNameResp) Reset()         { *m = GetUserByUserNameResp{} }
func (m *GetUserByUserNameResp) String() string { return proto.CompactTextString(m) }
func (*GetUserByUserNameResp) ProtoMessage()    {}
func (*GetUserByUserNameResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_53b9a3b79039de3a, []int{19}
}
func (m *GetUserByUserNameResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserByUserNameResp.Unmarshal(m, b)
}
func (m *GetUserByUserNameResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserByUserNameResp.Marshal(b, m, deterministic)
}
func (m *GetUserByUserNameResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserByUserNameResp.Merge(m, src)
}
func (m *GetUserByUserNameResp) XXX_Size() int {
	return xxx_messageInfo_GetUserByUserNameResp.Size(m)
}
func (m *GetUserByUserNameResp) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserByUserNameResp.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserByUserNameResp proto.InternalMessageInfo

func (m *GetUserByUserNameResp) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *GetUserByUserNameResp) GetAvatar() string {
	if m != nil {
		return m.Avatar
	}
	return ""
}

type GetUserByIdReq struct {
	UserId               string   `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserByIdReq) Reset()         { *m = GetUserByIdReq{} }
func (m *GetUserByIdReq) String() string { return proto.CompactTextString(m) }
func (*GetUserByIdReq) ProtoMessage()    {}
func (*GetUserByIdReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_53b9a3b79039de3a, []int{20}
}
func (m *GetUserByIdReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserByIdReq.Unmarshal(m, b)
}
func (m *GetUserByIdReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserByIdReq.Marshal(b, m, deterministic)
}
func (m *GetUserByIdReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserByIdReq.Merge(m, src)
}
func (m *GetUserByIdReq) XXX_Size() int {
	return xxx_messageInfo_GetUserByIdReq.Size(m)
}
func (m *GetUserByIdReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserByIdReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserByIdReq proto.InternalMessageInfo

func (m *GetUserByIdReq) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

type GetUserByIdResp struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Avatar               string   `protobuf:"bytes,2,opt,name=avatar,proto3" json:"avatar,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserByIdResp) Reset()         { *m = GetUserByIdResp{} }
func (m *GetUserByIdResp) String() string { return proto.CompactTextString(m) }
func (*GetUserByIdResp) ProtoMessage()    {}
func (*GetUserByIdResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_53b9a3b79039de3a, []int{21}
}
func (m *GetUserByIdResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserByIdResp.Unmarshal(m, b)
}
func (m *GetUserByIdResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserByIdResp.Marshal(b, m, deterministic)
}
func (m *GetUserByIdResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserByIdResp.Merge(m, src)
}
func (m *GetUserByIdResp) XXX_Size() int {
	return xxx_messageInfo_GetUserByIdResp.Size(m)
}
func (m *GetUserByIdResp) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserByIdResp.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserByIdResp proto.InternalMessageInfo

func (m *GetUserByIdResp) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *GetUserByIdResp) GetAvatar() string {
	if m != nil {
		return m.Avatar
	}
	return ""
}

type GetUserCommitRecordReq struct {
	UserId               int64    `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserCommitRecordReq) Reset()         { *m = GetUserCommitRecordReq{} }
func (m *GetUserCommitRecordReq) String() string { return proto.CompactTextString(m) }
func (*GetUserCommitRecordReq) ProtoMessage()    {}
func (*GetUserCommitRecordReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_53b9a3b79039de3a, []int{22}
}
func (m *GetUserCommitRecordReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserCommitRecordReq.Unmarshal(m, b)
}
func (m *GetUserCommitRecordReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserCommitRecordReq.Marshal(b, m, deterministic)
}
func (m *GetUserCommitRecordReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserCommitRecordReq.Merge(m, src)
}
func (m *GetUserCommitRecordReq) XXX_Size() int {
	return xxx_messageInfo_GetUserCommitRecordReq.Size(m)
}
func (m *GetUserCommitRecordReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserCommitRecordReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserCommitRecordReq proto.InternalMessageInfo

func (m *GetUserCommitRecordReq) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

type Commits struct {
	JudgeId              int64    `protobuf:"varint,1,opt,name=judge_id,json=judgeId,proto3" json:"judge_id,omitempty"`
	ProblemName          string   `protobuf:"bytes,2,opt,name=problem_name,json=problemName,proto3" json:"problem_name,omitempty"`
	CompileStatus        string   `protobuf:"bytes,3,opt,name=compile_status,json=compileStatus,proto3" json:"compile_status,omitempty"`
	JudgeStatus          string   `protobuf:"bytes,4,opt,name=judge_status,json=judgeStatus,proto3" json:"judge_status,omitempty"`
	CpuTimeUsed          string   `protobuf:"bytes,5,opt,name=cpu_time_used,json=cpuTimeUsed,proto3" json:"cpu_time_used,omitempty"`
	MemoryUsed           string   `protobuf:"bytes,6,opt,name=memory_used,json=memoryUsed,proto3" json:"memory_used,omitempty"`
	Language             string   `protobuf:"bytes,7,opt,name=language,proto3" json:"language,omitempty"`
	CreatedTime          string   `protobuf:"bytes,8,opt,name=created_time,json=createdTime,proto3" json:"created_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Commits) Reset()         { *m = Commits{} }
func (m *Commits) String() string { return proto.CompactTextString(m) }
func (*Commits) ProtoMessage()    {}
func (*Commits) Descriptor() ([]byte, []int) {
	return fileDescriptor_53b9a3b79039de3a, []int{23}
}
func (m *Commits) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Commits.Unmarshal(m, b)
}
func (m *Commits) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Commits.Marshal(b, m, deterministic)
}
func (m *Commits) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Commits.Merge(m, src)
}
func (m *Commits) XXX_Size() int {
	return xxx_messageInfo_Commits.Size(m)
}
func (m *Commits) XXX_DiscardUnknown() {
	xxx_messageInfo_Commits.DiscardUnknown(m)
}

var xxx_messageInfo_Commits proto.InternalMessageInfo

func (m *Commits) GetJudgeId() int64 {
	if m != nil {
		return m.JudgeId
	}
	return 0
}

func (m *Commits) GetProblemName() string {
	if m != nil {
		return m.ProblemName
	}
	return ""
}

func (m *Commits) GetCompileStatus() string {
	if m != nil {
		return m.CompileStatus
	}
	return ""
}

func (m *Commits) GetJudgeStatus() string {
	if m != nil {
		return m.JudgeStatus
	}
	return ""
}

func (m *Commits) GetCpuTimeUsed() string {
	if m != nil {
		return m.CpuTimeUsed
	}
	return ""
}

func (m *Commits) GetMemoryUsed() string {
	if m != nil {
		return m.MemoryUsed
	}
	return ""
}

func (m *Commits) GetLanguage() string {
	if m != nil {
		return m.Language
	}
	return ""
}

func (m *Commits) GetCreatedTime() string {
	if m != nil {
		return m.CreatedTime
	}
	return ""
}

type GetUserCommitRecordResp struct {
	Commits              []*Commits `protobuf:"bytes,1,rep,name=commits,proto3" json:"commits,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *GetUserCommitRecordResp) Reset()         { *m = GetUserCommitRecordResp{} }
func (m *GetUserCommitRecordResp) String() string { return proto.CompactTextString(m) }
func (*GetUserCommitRecordResp) ProtoMessage()    {}
func (*GetUserCommitRecordResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_53b9a3b79039de3a, []int{24}
}
func (m *GetUserCommitRecordResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserCommitRecordResp.Unmarshal(m, b)
}
func (m *GetUserCommitRecordResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserCommitRecordResp.Marshal(b, m, deterministic)
}
func (m *GetUserCommitRecordResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserCommitRecordResp.Merge(m, src)
}
func (m *GetUserCommitRecordResp) XXX_Size() int {
	return xxx_messageInfo_GetUserCommitRecordResp.Size(m)
}
func (m *GetUserCommitRecordResp) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserCommitRecordResp.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserCommitRecordResp proto.InternalMessageInfo

func (m *GetUserCommitRecordResp) GetCommits() []*Commits {
	if m != nil {
		return m.Commits
	}
	return nil
}

type PostCommentReq struct {
	Content              string   `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	ArticleId            int64    `protobuf:"varint,2,opt,name=article_id,json=articleId,proto3" json:"article_id,omitempty"`
	AuthorName           string   `protobuf:"bytes,3,opt,name=author_name,json=authorName,proto3" json:"author_name,omitempty"`
	AuthorAvatar         string   `protobuf:"bytes,4,opt,name=author_avatar,json=authorAvatar,proto3" json:"author_avatar,omitempty"`
	ParentId             int64    `protobuf:"varint,5,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	RootId               int64    `protobuf:"varint,6,opt,name=root_id,json=rootId,proto3" json:"root_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PostCommentReq) Reset()         { *m = PostCommentReq{} }
func (m *PostCommentReq) String() string { return proto.CompactTextString(m) }
func (*PostCommentReq) ProtoMessage()    {}
func (*PostCommentReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_53b9a3b79039de3a, []int{25}
}
func (m *PostCommentReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PostCommentReq.Unmarshal(m, b)
}
func (m *PostCommentReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PostCommentReq.Marshal(b, m, deterministic)
}
func (m *PostCommentReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PostCommentReq.Merge(m, src)
}
func (m *PostCommentReq) XXX_Size() int {
	return xxx_messageInfo_PostCommentReq.Size(m)
}
func (m *PostCommentReq) XXX_DiscardUnknown() {
	xxx_messageInfo_PostCommentReq.DiscardUnknown(m)
}

var xxx_messageInfo_PostCommentReq proto.InternalMessageInfo

func (m *PostCommentReq) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *PostCommentReq) GetArticleId() int64 {
	if m != nil {
		return m.ArticleId
	}
	return 0
}

func (m *PostCommentReq) GetAuthorName() string {
	if m != nil {
		return m.AuthorName
	}
	return ""
}

func (m *PostCommentReq) GetAuthorAvatar() string {
	if m != nil {
		return m.AuthorAvatar
	}
	return ""
}

func (m *PostCommentReq) GetParentId() int64 {
	if m != nil {
		return m.ParentId
	}
	return 0
}

func (m *PostCommentReq) GetRootId() int64 {
	if m != nil {
		return m.RootId
	}
	return 0
}

type PostCommentResp struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PostCommentResp) Reset()         { *m = PostCommentResp{} }
func (m *PostCommentResp) String() string { return proto.CompactTextString(m) }
func (*PostCommentResp) ProtoMessage()    {}
func (*PostCommentResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_53b9a3b79039de3a, []int{26}
}
func (m *PostCommentResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PostCommentResp.Unmarshal(m, b)
}
func (m *PostCommentResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PostCommentResp.Marshal(b, m, deterministic)
}
func (m *PostCommentResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PostCommentResp.Merge(m, src)
}
func (m *PostCommentResp) XXX_Size() int {
	return xxx_messageInfo_PostCommentResp.Size(m)
}
func (m *PostCommentResp) XXX_DiscardUnknown() {
	xxx_messageInfo_PostCommentResp.DiscardUnknown(m)
}

var xxx_messageInfo_PostCommentResp proto.InternalMessageInfo

type GetCommentsByArticleIdReq struct {
	ArticleId            int64    `protobuf:"varint,1,opt,name=article_id,json=articleId,proto3" json:"article_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetCommentsByArticleIdReq) Reset()         { *m = GetCommentsByArticleIdReq{} }
func (m *GetCommentsByArticleIdReq) String() string { return proto.CompactTextString(m) }
func (*GetCommentsByArticleIdReq) ProtoMessage()    {}
func (*GetCommentsByArticleIdReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_53b9a3b79039de3a, []int{27}
}
func (m *GetCommentsByArticleIdReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetCommentsByArticleIdReq.Unmarshal(m, b)
}
func (m *GetCommentsByArticleIdReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetCommentsByArticleIdReq.Marshal(b, m, deterministic)
}
func (m *GetCommentsByArticleIdReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetCommentsByArticleIdReq.Merge(m, src)
}
func (m *GetCommentsByArticleIdReq) XXX_Size() int {
	return xxx_messageInfo_GetCommentsByArticleIdReq.Size(m)
}
func (m *GetCommentsByArticleIdReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetCommentsByArticleIdReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetCommentsByArticleIdReq proto.InternalMessageInfo

func (m *GetCommentsByArticleIdReq) GetArticleId() int64 {
	if m != nil {
		return m.ArticleId
	}
	return 0
}

type Comments struct {
	Content              string   `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	AuthorName           string   `protobuf:"bytes,2,opt,name=author_name,json=authorName,proto3" json:"author_name,omitempty"`
	AuthorAvatar         string   `protobuf:"bytes,3,opt,name=author_avatar,json=authorAvatar,proto3" json:"author_avatar,omitempty"`
	ParentId             int64    `protobuf:"varint,4,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	RootId               int64    `protobuf:"varint,5,opt,name=root_id,json=rootId,proto3" json:"root_id,omitempty"`
	CreatedTime          string   `protobuf:"bytes,6,opt,name=created_time,json=createdTime,proto3" json:"created_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Comments) Reset()         { *m = Comments{} }
func (m *Comments) String() string { return proto.CompactTextString(m) }
func (*Comments) ProtoMessage()    {}
func (*Comments) Descriptor() ([]byte, []int) {
	return fileDescriptor_53b9a3b79039de3a, []int{28}
}
func (m *Comments) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Comments.Unmarshal(m, b)
}
func (m *Comments) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Comments.Marshal(b, m, deterministic)
}
func (m *Comments) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Comments.Merge(m, src)
}
func (m *Comments) XXX_Size() int {
	return xxx_messageInfo_Comments.Size(m)
}
func (m *Comments) XXX_DiscardUnknown() {
	xxx_messageInfo_Comments.DiscardUnknown(m)
}

var xxx_messageInfo_Comments proto.InternalMessageInfo

func (m *Comments) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *Comments) GetAuthorName() string {
	if m != nil {
		return m.AuthorName
	}
	return ""
}

func (m *Comments) GetAuthorAvatar() string {
	if m != nil {
		return m.AuthorAvatar
	}
	return ""
}

func (m *Comments) GetParentId() int64 {
	if m != nil {
		return m.ParentId
	}
	return 0
}

func (m *Comments) GetRootId() int64 {
	if m != nil {
		return m.RootId
	}
	return 0
}

func (m *Comments) GetCreatedTime() string {
	if m != nil {
		return m.CreatedTime
	}
	return ""
}

type GetCommentsByArticleIdResp struct {
	Comments             []*Comments `protobuf:"bytes,1,rep,name=comments,proto3" json:"comments,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *GetCommentsByArticleIdResp) Reset()         { *m = GetCommentsByArticleIdResp{} }
func (m *GetCommentsByArticleIdResp) String() string { return proto.CompactTextString(m) }
func (*GetCommentsByArticleIdResp) ProtoMessage()    {}
func (*GetCommentsByArticleIdResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_53b9a3b79039de3a, []int{29}
}
func (m *GetCommentsByArticleIdResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetCommentsByArticleIdResp.Unmarshal(m, b)
}
func (m *GetCommentsByArticleIdResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetCommentsByArticleIdResp.Marshal(b, m, deterministic)
}
func (m *GetCommentsByArticleIdResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetCommentsByArticleIdResp.Merge(m, src)
}
func (m *GetCommentsByArticleIdResp) XXX_Size() int {
	return xxx_messageInfo_GetCommentsByArticleIdResp.Size(m)
}
func (m *GetCommentsByArticleIdResp) XXX_DiscardUnknown() {
	xxx_messageInfo_GetCommentsByArticleIdResp.DiscardUnknown(m)
}

var xxx_messageInfo_GetCommentsByArticleIdResp proto.InternalMessageInfo

func (m *GetCommentsByArticleIdResp) GetComments() []*Comments {
	if m != nil {
		return m.Comments
	}
	return nil
}

type GetLastSevenCommentReq struct {
	ArticleId            int64    `protobuf:"varint,1,opt,name=article_id,json=articleId,proto3" json:"article_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetLastSevenCommentReq) Reset()         { *m = GetLastSevenCommentReq{} }
func (m *GetLastSevenCommentReq) String() string { return proto.CompactTextString(m) }
func (*GetLastSevenCommentReq) ProtoMessage()    {}
func (*GetLastSevenCommentReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_53b9a3b79039de3a, []int{30}
}
func (m *GetLastSevenCommentReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetLastSevenCommentReq.Unmarshal(m, b)
}
func (m *GetLastSevenCommentReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetLastSevenCommentReq.Marshal(b, m, deterministic)
}
func (m *GetLastSevenCommentReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetLastSevenCommentReq.Merge(m, src)
}
func (m *GetLastSevenCommentReq) XXX_Size() int {
	return xxx_messageInfo_GetLastSevenCommentReq.Size(m)
}
func (m *GetLastSevenCommentReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetLastSevenCommentReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetLastSevenCommentReq proto.InternalMessageInfo

func (m *GetLastSevenCommentReq) GetArticleId() int64 {
	if m != nil {
		return m.ArticleId
	}
	return 0
}

type GetLastSevenCommentResp struct {
	Comments             []*Comments `protobuf:"bytes,1,rep,name=comments,proto3" json:"comments,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *GetLastSevenCommentResp) Reset()         { *m = GetLastSevenCommentResp{} }
func (m *GetLastSevenCommentResp) String() string { return proto.CompactTextString(m) }
func (*GetLastSevenCommentResp) ProtoMessage()    {}
func (*GetLastSevenCommentResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_53b9a3b79039de3a, []int{31}
}
func (m *GetLastSevenCommentResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetLastSevenCommentResp.Unmarshal(m, b)
}
func (m *GetLastSevenCommentResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetLastSevenCommentResp.Marshal(b, m, deterministic)
}
func (m *GetLastSevenCommentResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetLastSevenCommentResp.Merge(m, src)
}
func (m *GetLastSevenCommentResp) XXX_Size() int {
	return xxx_messageInfo_GetLastSevenCommentResp.Size(m)
}
func (m *GetLastSevenCommentResp) XXX_DiscardUnknown() {
	xxx_messageInfo_GetLastSevenCommentResp.DiscardUnknown(m)
}

var xxx_messageInfo_GetLastSevenCommentResp proto.InternalMessageInfo

func (m *GetLastSevenCommentResp) GetComments() []*Comments {
	if m != nil {
		return m.Comments
	}
	return nil
}

type GetRandomCommentReq struct {
	ArticleId            int64    `protobuf:"varint,1,opt,name=article_id,json=articleId,proto3" json:"article_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetRandomCommentReq) Reset()         { *m = GetRandomCommentReq{} }
func (m *GetRandomCommentReq) String() string { return proto.CompactTextString(m) }
func (*GetRandomCommentReq) ProtoMessage()    {}
func (*GetRandomCommentReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_53b9a3b79039de3a, []int{32}
}
func (m *GetRandomCommentReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRandomCommentReq.Unmarshal(m, b)
}
func (m *GetRandomCommentReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRandomCommentReq.Marshal(b, m, deterministic)
}
func (m *GetRandomCommentReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRandomCommentReq.Merge(m, src)
}
func (m *GetRandomCommentReq) XXX_Size() int {
	return xxx_messageInfo_GetRandomCommentReq.Size(m)
}
func (m *GetRandomCommentReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRandomCommentReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetRandomCommentReq proto.InternalMessageInfo

func (m *GetRandomCommentReq) GetArticleId() int64 {
	if m != nil {
		return m.ArticleId
	}
	return 0
}

type GetRandomCommentResp struct {
	Comments             *Comments `protobuf:"bytes,1,opt,name=comments,proto3" json:"comments,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *GetRandomCommentResp) Reset()         { *m = GetRandomCommentResp{} }
func (m *GetRandomCommentResp) String() string { return proto.CompactTextString(m) }
func (*GetRandomCommentResp) ProtoMessage()    {}
func (*GetRandomCommentResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_53b9a3b79039de3a, []int{33}
}
func (m *GetRandomCommentResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRandomCommentResp.Unmarshal(m, b)
}
func (m *GetRandomCommentResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRandomCommentResp.Marshal(b, m, deterministic)
}
func (m *GetRandomCommentResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRandomCommentResp.Merge(m, src)
}
func (m *GetRandomCommentResp) XXX_Size() int {
	return xxx_messageInfo_GetRandomCommentResp.Size(m)
}
func (m *GetRandomCommentResp) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRandomCommentResp.DiscardUnknown(m)
}

var xxx_messageInfo_GetRandomCommentResp proto.InternalMessageInfo

func (m *GetRandomCommentResp) GetComments() *Comments {
	if m != nil {
		return m.Comments
	}
	return nil
}

type SubmitCodeReq struct {
	UserId               int64    `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	UserName             string   `protobuf:"bytes,2,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	ProblemId            int64    `protobuf:"varint,3,opt,name=problem_id,json=problemId,proto3" json:"problem_id,omitempty"`
	ProblemName          string   `protobuf:"bytes,4,opt,name=problem_name,json=problemName,proto3" json:"problem_name,omitempty"`
	Language             string   `protobuf:"bytes,5,opt,name=language,proto3" json:"language,omitempty"`
	Code                 string   `protobuf:"bytes,6,opt,name=code,proto3" json:"code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SubmitCodeReq) Reset()         { *m = SubmitCodeReq{} }
func (m *SubmitCodeReq) String() string { return proto.CompactTextString(m) }
func (*SubmitCodeReq) ProtoMessage()    {}
func (*SubmitCodeReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_53b9a3b79039de3a, []int{34}
}
func (m *SubmitCodeReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SubmitCodeReq.Unmarshal(m, b)
}
func (m *SubmitCodeReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SubmitCodeReq.Marshal(b, m, deterministic)
}
func (m *SubmitCodeReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SubmitCodeReq.Merge(m, src)
}
func (m *SubmitCodeReq) XXX_Size() int {
	return xxx_messageInfo_SubmitCodeReq.Size(m)
}
func (m *SubmitCodeReq) XXX_DiscardUnknown() {
	xxx_messageInfo_SubmitCodeReq.DiscardUnknown(m)
}

var xxx_messageInfo_SubmitCodeReq proto.InternalMessageInfo

func (m *SubmitCodeReq) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *SubmitCodeReq) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func (m *SubmitCodeReq) GetProblemId() int64 {
	if m != nil {
		return m.ProblemId
	}
	return 0
}

func (m *SubmitCodeReq) GetProblemName() string {
	if m != nil {
		return m.ProblemName
	}
	return ""
}

func (m *SubmitCodeReq) GetLanguage() string {
	if m != nil {
		return m.Language
	}
	return ""
}

func (m *SubmitCodeReq) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

type SubmitCodeResp struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SubmitCodeResp) Reset()         { *m = SubmitCodeResp{} }
func (m *SubmitCodeResp) String() string { return proto.CompactTextString(m) }
func (*SubmitCodeResp) ProtoMessage()    {}
func (*SubmitCodeResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_53b9a3b79039de3a, []int{35}
}
func (m *SubmitCodeResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SubmitCodeResp.Unmarshal(m, b)
}
func (m *SubmitCodeResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SubmitCodeResp.Marshal(b, m, deterministic)
}
func (m *SubmitCodeResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SubmitCodeResp.Merge(m, src)
}
func (m *SubmitCodeResp) XXX_Size() int {
	return xxx_messageInfo_SubmitCodeResp.Size(m)
}
func (m *SubmitCodeResp) XXX_DiscardUnknown() {
	xxx_messageInfo_SubmitCodeResp.DiscardUnknown(m)
}

var xxx_messageInfo_SubmitCodeResp proto.InternalMessageInfo

type UpdateCodeCompileStatusReq struct {
	CodeId               int64    `protobuf:"varint,1,opt,name=code_id,json=codeId,proto3" json:"code_id,omitempty"`
	CompileStatus        string   `protobuf:"bytes,2,opt,name=compile_status,json=compileStatus,proto3" json:"compile_status,omitempty"`
	CompileLog           string   `protobuf:"bytes,3,opt,name=compile_log,json=compileLog,proto3" json:"compile_log,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateCodeCompileStatusReq) Reset()         { *m = UpdateCodeCompileStatusReq{} }
func (m *UpdateCodeCompileStatusReq) String() string { return proto.CompactTextString(m) }
func (*UpdateCodeCompileStatusReq) ProtoMessage()    {}
func (*UpdateCodeCompileStatusReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_53b9a3b79039de3a, []int{36}
}
func (m *UpdateCodeCompileStatusReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateCodeCompileStatusReq.Unmarshal(m, b)
}
func (m *UpdateCodeCompileStatusReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateCodeCompileStatusReq.Marshal(b, m, deterministic)
}
func (m *UpdateCodeCompileStatusReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateCodeCompileStatusReq.Merge(m, src)
}
func (m *UpdateCodeCompileStatusReq) XXX_Size() int {
	return xxx_messageInfo_UpdateCodeCompileStatusReq.Size(m)
}
func (m *UpdateCodeCompileStatusReq) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateCodeCompileStatusReq.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateCodeCompileStatusReq proto.InternalMessageInfo

func (m *UpdateCodeCompileStatusReq) GetCodeId() int64 {
	if m != nil {
		return m.CodeId
	}
	return 0
}

func (m *UpdateCodeCompileStatusReq) GetCompileStatus() string {
	if m != nil {
		return m.CompileStatus
	}
	return ""
}

func (m *UpdateCodeCompileStatusReq) GetCompileLog() string {
	if m != nil {
		return m.CompileLog
	}
	return ""
}

type UpdateCodeCompileStatusResp struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateCodeCompileStatusResp) Reset()         { *m = UpdateCodeCompileStatusResp{} }
func (m *UpdateCodeCompileStatusResp) String() string { return proto.CompactTextString(m) }
func (*UpdateCodeCompileStatusResp) ProtoMessage()    {}
func (*UpdateCodeCompileStatusResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_53b9a3b79039de3a, []int{37}
}
func (m *UpdateCodeCompileStatusResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateCodeCompileStatusResp.Unmarshal(m, b)
}
func (m *UpdateCodeCompileStatusResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateCodeCompileStatusResp.Marshal(b, m, deterministic)
}
func (m *UpdateCodeCompileStatusResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateCodeCompileStatusResp.Merge(m, src)
}
func (m *UpdateCodeCompileStatusResp) XXX_Size() int {
	return xxx_messageInfo_UpdateCodeCompileStatusResp.Size(m)
}
func (m *UpdateCodeCompileStatusResp) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateCodeCompileStatusResp.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateCodeCompileStatusResp proto.InternalMessageInfo

type UpdateCodeJudgeStatusReq struct {
	CodeId               int64    `protobuf:"varint,1,opt,name=code_id,json=codeId,proto3" json:"code_id,omitempty"`
	CompileStatus        string   `protobuf:"bytes,2,opt,name=compile_status,json=compileStatus,proto3" json:"compile_status,omitempty"`
	JudgeStatus          string   `protobuf:"bytes,3,opt,name=judge_status,json=judgeStatus,proto3" json:"judge_status,omitempty"`
	CpuTimeUsed          string   `protobuf:"bytes,4,opt,name=cpu_time_used,json=cpuTimeUsed,proto3" json:"cpu_time_used,omitempty"`
	MemoryUsed           string   `protobuf:"bytes,5,opt,name=memory_used,json=memoryUsed,proto3" json:"memory_used,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateCodeJudgeStatusReq) Reset()         { *m = UpdateCodeJudgeStatusReq{} }
func (m *UpdateCodeJudgeStatusReq) String() string { return proto.CompactTextString(m) }
func (*UpdateCodeJudgeStatusReq) ProtoMessage()    {}
func (*UpdateCodeJudgeStatusReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_53b9a3b79039de3a, []int{38}
}
func (m *UpdateCodeJudgeStatusReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateCodeJudgeStatusReq.Unmarshal(m, b)
}
func (m *UpdateCodeJudgeStatusReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateCodeJudgeStatusReq.Marshal(b, m, deterministic)
}
func (m *UpdateCodeJudgeStatusReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateCodeJudgeStatusReq.Merge(m, src)
}
func (m *UpdateCodeJudgeStatusReq) XXX_Size() int {
	return xxx_messageInfo_UpdateCodeJudgeStatusReq.Size(m)
}
func (m *UpdateCodeJudgeStatusReq) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateCodeJudgeStatusReq.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateCodeJudgeStatusReq proto.InternalMessageInfo

func (m *UpdateCodeJudgeStatusReq) GetCodeId() int64 {
	if m != nil {
		return m.CodeId
	}
	return 0
}

func (m *UpdateCodeJudgeStatusReq) GetCompileStatus() string {
	if m != nil {
		return m.CompileStatus
	}
	return ""
}

func (m *UpdateCodeJudgeStatusReq) GetJudgeStatus() string {
	if m != nil {
		return m.JudgeStatus
	}
	return ""
}

func (m *UpdateCodeJudgeStatusReq) GetCpuTimeUsed() string {
	if m != nil {
		return m.CpuTimeUsed
	}
	return ""
}

func (m *UpdateCodeJudgeStatusReq) GetMemoryUsed() string {
	if m != nil {
		return m.MemoryUsed
	}
	return ""
}

type UpdateCodeJudgeStatusResp struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateCodeJudgeStatusResp) Reset()         { *m = UpdateCodeJudgeStatusResp{} }
func (m *UpdateCodeJudgeStatusResp) String() string { return proto.CompactTextString(m) }
func (*UpdateCodeJudgeStatusResp) ProtoMessage()    {}
func (*UpdateCodeJudgeStatusResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_53b9a3b79039de3a, []int{39}
}
func (m *UpdateCodeJudgeStatusResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateCodeJudgeStatusResp.Unmarshal(m, b)
}
func (m *UpdateCodeJudgeStatusResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateCodeJudgeStatusResp.Marshal(b, m, deterministic)
}
func (m *UpdateCodeJudgeStatusResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateCodeJudgeStatusResp.Merge(m, src)
}
func (m *UpdateCodeJudgeStatusResp) XXX_Size() int {
	return xxx_messageInfo_UpdateCodeJudgeStatusResp.Size(m)
}
func (m *UpdateCodeJudgeStatusResp) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateCodeJudgeStatusResp.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateCodeJudgeStatusResp proto.InternalMessageInfo

func init() {
	proto.RegisterType((*PostProblemReq)(nil), "service.problem.api.PostProblemReq")
	proto.RegisterType((*PostProblemResp)(nil), "service.problem.api.PostProblemResp")
	proto.RegisterType((*GetProblemByIdReq)(nil), "service.problem.api.GetProblemByIdReq")
	proto.RegisterType((*GetProblemByIdResp)(nil), "service.problem.api.GetProblemByIdResp")
	proto.RegisterType((*GetProblemByPageReq)(nil), "service.problem.api.GetProblemByPageReq")
	proto.RegisterType((*ProblemPageDetail)(nil), "service.problem.api.ProblemPageDetail")
	proto.RegisterType((*GetProblemByPageResp)(nil), "service.problem.api.GetProblemByPageResp")
	proto.RegisterType((*PostArticleReq)(nil), "service.problem.api.PostArticleReq")
	proto.RegisterType((*PostArticleResp)(nil), "service.problem.api.PostArticleResp")
	proto.RegisterType((*GetArticleByIdReq)(nil), "service.problem.api.GetArticleByIdReq")
	proto.RegisterType((*GetArticleByIdResp)(nil), "service.problem.api.GetArticleByIdResp")
	proto.RegisterType((*GetArticleByPageReq)(nil), "service.problem.api.GetArticleByPageReq")
	proto.RegisterType((*ArticlePageDetail)(nil), "service.problem.api.ArticlePageDetail")
	proto.RegisterType((*GetArticleByPageResp)(nil), "service.problem.api.GetArticleByPageResp")
	proto.RegisterType((*LoginReq)(nil), "service.problem.api.LoginReq")
	proto.RegisterType((*LoginResp)(nil), "service.problem.api.LoginResp")
	proto.RegisterType((*RegisterReq)(nil), "service.problem.api.RegisterReq")
	proto.RegisterType((*RegisterResp)(nil), "service.problem.api.RegisterResp")
	proto.RegisterType((*GetUserByUserNameReq)(nil), "service.problem.api.GetUserByUserNameReq")
	proto.RegisterType((*GetUserByUserNameResp)(nil), "service.problem.api.GetUserByUserNameResp")
	proto.RegisterType((*GetUserByIdReq)(nil), "service.problem.api.GetUserByIdReq")
	proto.RegisterType((*GetUserByIdResp)(nil), "service.problem.api.GetUserByIdResp")
	proto.RegisterType((*GetUserCommitRecordReq)(nil), "service.problem.api.GetUserCommitRecordReq")
	proto.RegisterType((*Commits)(nil), "service.problem.api.Commits")
	proto.RegisterType((*GetUserCommitRecordResp)(nil), "service.problem.api.GetUserCommitRecordResp")
	proto.RegisterType((*PostCommentReq)(nil), "service.problem.api.PostCommentReq")
	proto.RegisterType((*PostCommentResp)(nil), "service.problem.api.PostCommentResp")
	proto.RegisterType((*GetCommentsByArticleIdReq)(nil), "service.problem.api.GetCommentsByArticleIdReq")
	proto.RegisterType((*Comments)(nil), "service.problem.api.Comments")
	proto.RegisterType((*GetCommentsByArticleIdResp)(nil), "service.problem.api.GetCommentsByArticleIdResp")
	proto.RegisterType((*GetLastSevenCommentReq)(nil), "service.problem.api.GetLastSevenCommentReq")
	proto.RegisterType((*GetLastSevenCommentResp)(nil), "service.problem.api.GetLastSevenCommentResp")
	proto.RegisterType((*GetRandomCommentReq)(nil), "service.problem.api.GetRandomCommentReq")
	proto.RegisterType((*GetRandomCommentResp)(nil), "service.problem.api.GetRandomCommentResp")
	proto.RegisterType((*SubmitCodeReq)(nil), "service.problem.api.SubmitCodeReq")
	proto.RegisterType((*SubmitCodeResp)(nil), "service.problem.api.SubmitCodeResp")
	proto.RegisterType((*UpdateCodeCompileStatusReq)(nil), "service.problem.api.UpdateCodeCompileStatusReq")
	proto.RegisterType((*UpdateCodeCompileStatusResp)(nil), "service.problem.api.UpdateCodeCompileStatusResp")
	proto.RegisterType((*UpdateCodeJudgeStatusReq)(nil), "service.problem.api.UpdateCodeJudgeStatusReq")
	proto.RegisterType((*UpdateCodeJudgeStatusResp)(nil), "service.problem.api.UpdateCodeJudgeStatusResp")
}

func init() { proto.RegisterFile("interact_hub.proto", fileDescriptor_53b9a3b79039de3a) }

var fileDescriptor_53b9a3b79039de3a = []byte{
	// 1704 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x59, 0x4b, 0x6f, 0x1b, 0x47,
	0x12, 0xc6, 0x90, 0xa2, 0x48, 0x15, 0xf5, 0xb0, 0x5a, 0xb2, 0x45, 0x8d, 0xac, 0xb5, 0xdc, 0xf2,
	0x43, 0xf2, 0x43, 0x5a, 0x6b, 0x17, 0xbb, 0x58, 0xef, 0xc9, 0x92, 0x17, 0x86, 0x76, 0xbd, 0x86,
	0x4c, 0xd9, 0x58, 0xac, 0x2f, 0xc4, 0x88, 0xd3, 0xa6, 0x27, 0xe1, 0xcc, 0x74, 0xa6, 0x87, 0x0a,
	0x64, 0x47, 0x17, 0x23, 0x87, 0x5c, 0x83, 0x24, 0xb7, 0x20, 0x39, 0xe4, 0x9e, 0x63, 0x72, 0x4f,
	0x90, 0x5f, 0x10, 0xe4, 0x1f, 0xe4, 0x47, 0xe4, 0x18, 0xf4, 0x6b, 0xde, 0x43, 0x52, 0xb1, 0x2e,
	0x02, 0xbb, 0xba, 0xba, 0xba, 0x1e, 0xdf, 0x7c, 0x5d, 0x05, 0x01, 0x72, 0xbc, 0x90, 0x04, 0x56,
	0x37, 0xec, 0xbc, 0x1a, 0x1c, 0x6d, 0xd1, 0xc0, 0x0f, 0x7d, 0xb4, 0xc0, 0x48, 0x70, 0xec, 0x74,
	0x09, 0x5f, 0x1e, 0xf5, 0x89, 0xbb, 0x65, 0x51, 0xc7, 0xbc, 0xdc, 0xf3, 0xfd, 0x5e, 0x9f, 0x6c,
	0x5b, 0xd4, 0xd9, 0xb6, 0x3c, 0xcf, 0x0f, 0xad, 0xd0, 0xf1, 0x3d, 0x26, 0x8f, 0xe0, 0x6f, 0x0d,
	0x98, 0x3d, 0xf0, 0x59, 0x78, 0x20, 0x4f, 0xb4, 0xc9, 0x07, 0x68, 0x15, 0x40, 0x9d, 0xef, 0x38,
	0x76, 0xcb, 0x58, 0x33, 0x36, 0xaa, 0xed, 0x29, 0x25, 0xd9, 0xb7, 0xd1, 0x3a, 0xcc, 0xe8, 0xed,
	0xd0, 0x09, 0xfb, 0xa4, 0x55, 0x59, 0x33, 0x36, 0xa6, 0xda, 0xd3, 0x4a, 0xf8, 0x8c, 0xcb, 0xd0,
	0x36, 0x2c, 0x68, 0x25, 0x9b, 0xb0, 0x6e, 0xe0, 0x50, 0x7e, 0x69, 0xab, 0x2a, 0x54, 0x91, 0xda,
	0x7a, 0x18, 0xef, 0xa0, 0x9b, 0x30, 0xa7, 0x0f, 0x74, 0x7d, 0x2f, 0x24, 0x5e, 0xd8, 0x9a, 0x10,
	0xca, 0xb3, 0x4a, 0xbc, 0x27, 0xa5, 0x78, 0x1e, 0xe6, 0x52, 0xfe, 0x32, 0x8a, 0x77, 0x60, 0xfe,
	0x11, 0xd1, 0x92, 0xdd, 0x93, 0x7d, 0x7b, 0x74, 0x14, 0xf8, 0x3b, 0x03, 0x50, 0xf6, 0x10, 0xa3,
	0xf9, 0xe0, 0x8c, 0xf1, 0x83, 0xab, 0x9c, 0x25, 0xb8, 0x6a, 0x51, 0x70, 0xe8, 0x2a, 0x4c, 0x77,
	0x03, 0x62, 0x85, 0xc4, 0xee, 0x84, 0x8e, 0x4b, 0x54, 0x0a, 0x9a, 0x4a, 0xf6, 0xcc, 0x71, 0x09,
	0xfe, 0x2f, 0x2c, 0x24, 0xfd, 0x3e, 0xb0, 0x7a, 0x84, 0x87, 0xbb, 0x0c, 0x0d, 0x6a, 0xf5, 0x48,
	0xc7, 0x1b, 0xb8, 0x2a, 0xd8, 0x3a, 0x5f, 0x3f, 0x19, 0xb8, 0x68, 0x05, 0xa6, 0xc4, 0x16, 0x73,
	0x5e, 0xcb, 0x62, 0x55, 0xdb, 0x42, 0xf7, 0xd0, 0x79, 0x4d, 0xf0, 0x6b, 0x98, 0x57, 0xb6, 0xb8,
	0xa5, 0x87, 0x24, 0xb4, 0x9c, 0xfe, 0xb9, 0x20, 0x20, 0x1b, 0x4a, 0x35, 0x1f, 0xca, 0x0b, 0x58,
	0xcc, 0x87, 0xc2, 0x28, 0xda, 0x85, 0x86, 0x32, 0xc5, 0x5a, 0xc6, 0x5a, 0x75, 0xa3, 0xb9, 0x73,
	0x63, 0xab, 0x00, 0xd9, 0x5b, 0x39, 0xc7, 0xdb, 0xd1, 0xb9, 0x08, 0xd7, 0x0f, 0x82, 0xd0, 0xe9,
	0xf6, 0x89, 0x42, 0x84, 0x25, 0x57, 0x89, 0xa8, 0x94, 0x44, 0x46, 0xa5, 0xb7, 0x53, 0x51, 0x29,
	0x61, 0x54, 0x7a, 0xad, 0x54, 0x80, 0x6b, 0xb5, 0x95, 0x29, 0xbd, 0x3e, 0x90, 0xc1, 0xb5, 0x12,
	0x67, 0x70, 0x1d, 0xf9, 0x1b, 0xe1, 0x5a, 0x49, 0x12, 0xb8, 0x1e, 0x12, 0x85, 0xc6, 0x75, 0xea,
	0x90, 0xc4, 0x75, 0x3a, 0x38, 0x63, 0xfc, 0xe0, 0x2a, 0x67, 0x09, 0xae, 0x5a, 0x14, 0xdc, 0xf8,
	0xb8, 0x8e, 0xfc, 0x3e, 0x07, 0x5c, 0x2b, 0x5b, 0x69, 0x5c, 0xbf, 0x33, 0x02, 0xc6, 0xc6, 0x75,
	0x26, 0x14, 0x89, 0x6b, 0x65, 0x6a, 0x38, 0xae, 0x73, 0x8e, 0xb7, 0xa3, 0x73, 0x78, 0x17, 0x1a,
	0x8f, 0xfd, 0x9e, 0xe3, 0xf1, 0xdc, 0x98, 0xd0, 0x18, 0x30, 0x12, 0x78, 0x96, 0xab, 0xeb, 0x19,
	0xad, 0xf9, 0x1e, 0xb5, 0x18, 0xfb, 0xd0, 0x0f, 0x6c, 0x15, 0x46, 0xb4, 0xc6, 0x1e, 0x4c, 0x29,
	0x1b, 0x8c, 0xa2, 0x45, 0xa8, 0x85, 0xfe, 0xfb, 0xc4, 0x53, 0x16, 0xe4, 0x22, 0x65, 0xba, 0x92,
	0x31, 0xbd, 0x04, 0x75, 0xfe, 0x9b, 0xa7, 0xb0, 0x2a, 0x52, 0x38, 0xc9, 0x97, 0xfb, 0x36, 0xba,
	0x04, 0x93, 0xd6, 0xb1, 0x15, 0x5a, 0x81, 0xaa, 0xaf, 0x5a, 0x61, 0x0a, 0xcd, 0x36, 0xe9, 0x39,
	0x2c, 0x24, 0xc1, 0x3b, 0xb8, 0x8d, 0x36, 0xe1, 0x42, 0xd7, 0xf7, 0x5e, 0x3a, 0x81, 0xdb, 0x89,
	0x74, 0x64, 0xf6, 0xe7, 0x94, 0xfc, 0x40, 0x47, 0xf8, 0x7f, 0x98, 0x8e, 0x6f, 0x3c, 0xd7, 0x20,
	0xf1, 0x8e, 0x28, 0xee, 0x73, 0x46, 0x82, 0xdd, 0x13, 0xfe, 0xf7, 0x89, 0xe5, 0x92, 0x11, 0x51,
	0xe1, 0xff, 0xc0, 0xc5, 0x82, 0x33, 0x8c, 0x0e, 0x4d, 0x45, 0x9c, 0xcd, 0x4a, 0x2a, 0x9b, 0x9b,
	0x30, 0x1b, 0x19, 0x93, 0x94, 0x90, 0xf0, 0x55, 0x1a, 0xd1, 0xbe, 0xfe, 0x0b, 0xe6, 0x52, 0xaa,
	0x7f, 0xf0, 0xc6, 0x7b, 0x70, 0x49, 0x99, 0xd9, 0xf3, 0x5d, 0xd7, 0x09, 0xdb, 0xa4, 0xeb, 0x07,
	0x45, 0x37, 0xc7, 0x59, 0xfa, 0xa2, 0x02, 0x75, 0xa9, 0xcc, 0xf8, 0x27, 0xfc, 0xde, 0xc0, 0xee,
	0x25, 0xbe, 0xb9, 0xba, 0x58, 0xef, 0xdb, 0xfc, 0x63, 0xd2, 0x2f, 0x49, 0xa2, 0x0a, 0x4d, 0x25,
	0xe3, 0x69, 0x42, 0xd7, 0x61, 0xb6, 0xeb, 0xbb, 0xd4, 0xe9, 0x93, 0x0e, 0x0b, 0xad, 0x70, 0xc0,
	0x54, 0xcd, 0x67, 0x94, 0xf4, 0x50, 0x08, 0xb9, 0x25, 0x79, 0x89, 0x52, 0x52, 0x0c, 0x23, 0x64,
	0x4a, 0x05, 0xc3, 0x4c, 0x97, 0x0e, 0xc4, 0x57, 0xdb, 0x19, 0x30, 0x62, 0xb7, 0x6a, 0xea, 0xd3,
	0xa5, 0x03, 0xfe, 0xd9, 0x3e, 0x67, 0xc4, 0x46, 0x57, 0xa0, 0xe9, 0x12, 0xd7, 0x0f, 0x4e, 0xa4,
	0xc6, 0xa4, 0xd0, 0x00, 0x29, 0x12, 0x0a, 0x26, 0x34, 0xfa, 0x96, 0xd7, 0x1b, 0x58, 0x3d, 0xd2,
	0xaa, 0xcb, 0xfc, 0xe9, 0x75, 0x8e, 0x1a, 0x1a, 0x79, 0x6a, 0x78, 0x0a, 0x4b, 0x85, 0xa9, 0x64,
	0x14, 0xfd, 0x0d, 0xea, 0x5d, 0x99, 0x31, 0x45, 0x0e, 0x97, 0x0b, 0xc9, 0x41, 0x65, 0xb5, 0xad,
	0x95, 0xf1, 0x4f, 0xea, 0xa5, 0xe3, 0x1b, 0xc4, 0x0b, 0x79, 0x59, 0x5a, 0xdc, 0x94, 0xe4, 0x63,
	0x59, 0x63, 0xbd, 0xcc, 0x30, 0x60, 0x25, 0xcb, 0x80, 0x57, 0xa0, 0x69, 0x0d, 0xc2, 0x57, 0x7e,
	0x20, 0xcb, 0x21, 0x33, 0x0d, 0x52, 0x24, 0xaa, 0xc1, 0x29, 0x52, 0x2a, 0xa4, 0xbe, 0xf4, 0x69,
	0x29, 0x7c, 0x20, 0x64, 0x92, 0x98, 0x03, 0xe2, 0x85, 0xfc, 0x8e, 0x9a, 0x26, 0x66, 0x2e, 0xd8,
	0xb7, 0x39, 0x64, 0x02, 0xdf, 0x17, 0x5b, 0x93, 0x12, 0x32, 0x7c, 0xb9, 0x6f, 0xeb, 0x07, 0x30,
	0x0a, 0x83, 0x51, 0x7c, 0x1f, 0x96, 0x1f, 0x11, 0x2d, 0x61, 0xbb, 0x27, 0x0f, 0xb4, 0xa3, 0x63,
	0x3c, 0x84, 0x3f, 0x1a, 0xd0, 0xd0, 0x27, 0x87, 0x24, 0x24, 0x13, 0x71, 0x65, 0x74, 0xc4, 0xd5,
	0x51, 0x11, 0x4f, 0x94, 0x47, 0x5c, 0x4b, 0x46, 0x9c, 0xc3, 0xcb, 0x64, 0x1e, 0x2f, 0xff, 0x03,
	0xb3, 0x2c, 0x03, 0x8c, 0xa2, 0x7f, 0x40, 0xa3, 0xab, 0xb6, 0x14, 0x66, 0x56, 0x4b, 0x31, 0xc3,
	0x95, 0xda, 0x91, 0x3a, 0xfe, 0xbb, 0xf8, 0xa6, 0x1f, 0x5b, 0x2c, 0x3c, 0x24, 0xc7, 0xc4, 0x4b,
	0x80, 0x67, 0x44, 0x5e, 0x9f, 0x09, 0x04, 0xe7, 0x0f, 0xbe, 0x9b, 0x3b, 0x7f, 0x15, 0xaf, 0x7f,
	0xdb, 0xf2, 0x6c, 0xdf, 0x1d, 0xdf, 0x97, 0xa7, 0x82, 0x8b, 0x33, 0xa7, 0x72, 0x8e, 0x18, 0x67,
	0x71, 0xe4, 0x7b, 0x03, 0x66, 0x0e, 0x07, 0x47, 0xae, 0x13, 0xee, 0xf9, 0x36, 0x19, 0xc6, 0x71,
	0xbc, 0xe8, 0x62, 0x23, 0xfb, 0x7e, 0x08, 0xd8, 0xa4, 0x5b, 0xe8, 0x6a, 0xb6, 0x85, 0xce, 0x12,
	0xdf, 0x44, 0x9e, 0xf8, 0x92, 0x4c, 0x53, 0xcb, 0x30, 0x0d, 0x82, 0x89, 0xae, 0x6f, 0x6b, 0xc4,
	0x88, 0xdf, 0xf8, 0x02, 0xcc, 0x26, 0x1d, 0x67, 0x14, 0x9f, 0x82, 0xf9, 0x9c, 0xda, 0x56, 0x48,
	0xb8, 0x64, 0x2f, 0x49, 0x97, 0x2a, 0x2e, 0x7e, 0x2e, 0x11, 0x17, 0x5f, 0xee, 0xdb, 0x05, 0x8c,
	0x5b, 0x29, 0x62, 0xdc, 0x2b, 0xd0, 0xd4, 0x6a, 0x7d, 0xbf, 0xa7, 0xb9, 0x42, 0x89, 0x1e, 0xfb,
	0x3d, 0xbc, 0x0a, 0x2b, 0xa5, 0xd7, 0x33, 0x8a, 0x7f, 0x30, 0xa0, 0x15, 0xef, 0xff, 0x3b, 0x26,
	0xea, 0xf3, 0x70, 0x2e, 0xfb, 0x1c, 0x54, 0xc7, 0x78, 0x0e, 0x26, 0x46, 0x3e, 0x07, 0xb5, 0xec,
	0x73, 0x80, 0x57, 0x60, 0xb9, 0x24, 0x06, 0x46, 0x77, 0xbe, 0xae, 0x42, 0x5d, 0xcd, 0x28, 0xe8,
	0x18, 0x9a, 0x89, 0xb1, 0x15, 0xad, 0x17, 0x0f, 0x34, 0xa9, 0x41, 0xdc, 0xbc, 0x36, 0x5a, 0x89,
	0x51, 0x7c, 0xf9, 0xed, 0xcf, 0xbf, 0x7e, 0x56, 0xb9, 0x84, 0xe7, 0xc5, 0x84, 0xaf, 0x34, 0xb7,
	0xa9, 0xcf, 0xc2, 0xfb, 0xc6, 0x2d, 0xf4, 0xb1, 0x21, 0xda, 0x85, 0xc4, 0x9c, 0x8b, 0x8a, 0x9b,
	0xce, 0xdc, 0x04, 0x6d, 0xde, 0x1c, 0x4b, 0x8f, 0x51, 0x7c, 0x55, 0x78, 0xb0, 0x82, 0x96, 0x53,
	0x1e, 0xbc, 0x89, 0xf1, 0x7f, 0x8a, 0x3e, 0x37, 0xe0, 0x42, 0x76, 0xd6, 0x43, 0x1b, 0x23, 0x2f,
	0x50, 0x53, 0x80, 0xb9, 0x39, 0xa6, 0x26, 0xa3, 0xf8, 0xb6, 0x70, 0xe6, 0x3a, 0x5a, 0xcf, 0x38,
	0xa3, 0x27, 0x85, 0x53, 0xf5, 0xdb, 0x1b, 0xb8, 0xa7, 0xa2, 0x42, 0x8a, 0x52, 0x75, 0x85, 0xf4,
	0xb2, 0xbc, 0x42, 0xf1, 0x48, 0x39, 0xa4, 0x42, 0xc9, 0x39, 0x2e, 0x5d, 0x21, 0x45, 0x5f, 0xd9,
	0x0a, 0x25, 0x26, 0xb6, 0xf2, 0x0a, 0xa5, 0x67, 0xc1, 0xf2, 0x0a, 0x65, 0xc6, 0xbf, 0x4c, 0x85,
	0xb4, 0x07, 0x6f, 0x62, 0x6e, 0x8d, 0x2a, 0x94, 0x9a, 0x5a, 0xca, 0x2b, 0x94, 0x9d, 0xd3, 0xca,
	0x2b, 0x94, 0x1b, 0x83, 0x32, 0x15, 0x8a, 0x9c, 0x29, 0xae, 0xd0, 0xdb, 0x1a, 0x4c, 0xf0, 0x76,
	0x09, 0x1d, 0x41, 0x4d, 0x0c, 0x2d, 0xa8, 0x98, 0xca, 0xf5, 0x50, 0x64, 0xfe, 0x69, 0xd8, 0x36,
	0xa3, 0xd8, 0x14, 0xb7, 0x2f, 0xe2, 0x39, 0x71, 0x3b, 0xe7, 0xeb, 0xed, 0x3e, 0xdf, 0xe4, 0xa5,
	0xf0, 0xa0, 0xa1, 0xc7, 0x06, 0xb4, 0x56, 0x68, 0x27, 0x31, 0xc7, 0x98, 0x57, 0x47, 0x68, 0x30,
	0x8a, 0x57, 0xc5, 0x65, 0x4b, 0x18, 0xc5, 0x97, 0x05, 0x6a, 0x9f, 0xdf, 0xf7, 0x89, 0x21, 0x26,
	0xfc, 0xf4, 0x60, 0x80, 0x4a, 0x53, 0x99, 0x1b, 0x3a, 0xcc, 0x5b, 0xe3, 0xaa, 0xc6, 0x28, 0x44,
	0x8b, 0xb1, 0x2f, 0x6f, 0x74, 0xeb, 0x7f, 0x8a, 0x06, 0xd0, 0x4c, 0x8c, 0x0a, 0x25, 0xe8, 0x4f,
	0xcf, 0x1d, 0x25, 0xe8, 0xcf, 0x4c, 0x1c, 0x78, 0x45, 0xdc, 0x7b, 0x11, 0x2d, 0x64, 0xee, 0x15,
	0xa8, 0xfb, 0xc6, 0x10, 0x0f, 0x7f, 0xb6, 0x21, 0x46, 0xb7, 0x87, 0x99, 0xce, 0x4c, 0x21, 0xe6,
	0x9d, 0xf1, 0x95, 0x19, 0xc5, 0xf7, 0x84, 0x3f, 0xb7, 0xd1, 0x66, 0xec, 0x0f, 0x0d, 0xfc, 0x97,
	0x0e, 0xc7, 0xa0, 0xf6, 0x6b, 0x5b, 0x36, 0xd7, 0x77, 0x03, 0x71, 0x6c, 0xe7, 0x97, 0x09, 0x39,
	0xcd, 0xf0, 0x86, 0x51, 0xd1, 0x84, 0x5e, 0x96, 0xd3, 0x44, 0xdc, 0xc6, 0x0c, 0xa1, 0x89, 0x64,
	0xb7, 0x9b, 0xa6, 0x09, 0xd5, 0x91, 0x44, 0x34, 0xf1, 0xa5, 0x21, 0x3a, 0xb6, 0x82, 0x56, 0x10,
	0x6d, 0x95, 0xc5, 0x5f, 0xdc, 0x39, 0x9b, 0xdb, 0x67, 0xd2, 0xcf, 0xd1, 0x87, 0xf6, 0x2c, 0x45,
	0x1f, 0x5f, 0xc9, 0x42, 0x66, 0xfb, 0xc2, 0xf2, 0x42, 0x16, 0xb4, 0x9e, 0xe5, 0x85, 0x2c, 0x6a,
	0x37, 0xf1, 0x1d, 0xe1, 0xd5, 0x0d, 0x74, 0x2d, 0xe5, 0x55, 0xdf, 0x62, 0x61, 0x87, 0x71, 0xdd,
	0xb4, 0x83, 0x9f, 0x4a, 0x7e, 0x4b, 0x35, 0x8b, 0xe5, 0xfc, 0x96, 0xed, 0x44, 0xcb, 0xf9, 0x2d,
	0xd7, 0x7d, 0xe2, 0x0d, 0xe1, 0x17, 0x46, 0x6b, 0x29, 0xbf, 0x02, 0xa1, 0x97, 0xf2, 0x69, 0xe7,
	0xb7, 0x0a, 0xcc, 0xf2, 0xc6, 0xe1, 0x20, 0xf0, 0xbb, 0x84, 0x31, 0xc7, 0xeb, 0x21, 0x0a, 0x10,
	0x77, 0x71, 0x08, 0x17, 0xde, 0x9a, 0xea, 0x4f, 0xcd, 0xf5, 0x91, 0x3a, 0x8c, 0xe2, 0x65, 0xe1,
	0xd3, 0x02, 0x9e, 0x55, 0x3e, 0xd9, 0xf1, 0xfb, 0xf3, 0x11, 0x2c, 0x95, 0xb4, 0x69, 0xa8, 0x18,
	0x28, 0xe5, 0x3d, 0xa5, 0xf9, 0xe7, 0xb3, 0x1d, 0x60, 0x14, 0x1d, 0xc3, 0xc5, 0xc2, 0x06, 0x0a,
	0xdd, 0x1d, 0x61, 0x2a, 0xdd, 0x30, 0x9a, 0x5b, 0x67, 0x51, 0x67, 0x74, 0xb7, 0xfe, 0xa2, 0xb6,
	0xf5, 0x4f, 0x8b, 0x3a, 0x47, 0x93, 0xe2, 0xff, 0x20, 0x7f, 0xf9, 0x3d, 0x00, 0x00, 0xff, 0xff,
	0x15, 0xcf, 0xe7, 0x02, 0x50, 0x19, 0x00, 0x00,
}
